### ISSUE TITLE
ceph.restart appears to be broken

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#1081]
### Description of Issue/Question

When I run `salt-run state.orch ceph.restart` after completing Stages 0-3, the orchestration fails like so:

```
2018-04-13T10:25:29.106 INFO:teuthology.orchestra.run.target213032075235.stderr:+ salt-run state.orch ceph.restart
...
... DEBUG spam omitted
...
2018-04-13T10:25:34.294 INFO:teuthology.orchestra.run.target213032075235.stderr:[DEBUG   ] Failed to import runners fs:
2018-04-13T10:25:34.294 INFO:teuthology.orchestra.run.target213032075235.stderr:Traceback (most recent call last):
2018-04-13T10:25:34.294 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1452, in _load_module
2018-04-13T10:25:34.294 INFO:teuthology.orchestra.run.target213032075235.stderr:    mod = spec.loader.load_module()
2018-04-13T10:25:34.294 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
2018-04-13T10:25:34.295 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 823, in load_module
2018-04-13T10:25:34.295 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 682, in load_module
2018-04-13T10:25:34.295 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
2018-04-13T10:25:34.295 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 684, in _load
2018-04-13T10:25:34.295 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2018-04-13T10:25:34.295 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2018-04-13T10:25:34.295 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2018-04-13T10:25:34.295 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "/srv/modules/runners/fs.py", line 21, in <module>
2018-04-13T10:25:34.295 INFO:teuthology.orchestra.run.target213032075235.stderr:    from deepsea_minions import DeepseaMinions
2018-04-13T10:25:34.296 INFO:teuthology.orchestra.run.target213032075235.stderr:ModuleNotFoundError: No module named 'deepsea_minions'
2018-04-13T10:25:34.308 INFO:teuthology.orchestra.run.target213032075235.stderr:[DEBUG   ] Failed to import runners populate:
2018-04-13T10:25:34.308 INFO:teuthology.orchestra.run.target213032075235.stderr:Traceback (most recent call last):
2018-04-13T10:25:34.308 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1452, in _load_module
2018-04-13T10:25:34.308 INFO:teuthology.orchestra.run.target213032075235.stderr:    mod = spec.loader.load_module()
2018-04-13T10:25:34.308 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
2018-04-13T10:25:34.309 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 823, in load_module
2018-04-13T10:25:34.309 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 682, in load_module
2018-04-13T10:25:34.309 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
2018-04-13T10:25:34.309 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 684, in _load
2018-04-13T10:25:34.309 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2018-04-13T10:25:34.309 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2018-04-13T10:25:34.309 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2018-04-13T10:25:34.309 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "/srv/modules/runners/populate.py", line 32, in <module>
2018-04-13T10:25:34.309 INFO:teuthology.orchestra.run.target213032075235.stderr:    import ready
2018-04-13T10:25:34.309 INFO:teuthology.orchestra.run.target213032075235.stderr:ModuleNotFoundError: No module named 'ready'
2018-04-13T10:25:34.310 INFO:teuthology.orchestra.run.target213032075235.stderr:[DEBUG   ] Failed to import runners proposal:
2018-04-13T10:25:34.310 INFO:teuthology.orchestra.run.target213032075235.stderr:Traceback (most recent call last):
2018-04-13T10:25:34.310 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1452, in _load_module
2018-04-13T10:25:34.310 INFO:teuthology.orchestra.run.target213032075235.stderr:    mod = spec.loader.load_module()
2018-04-13T10:25:34.310 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
2018-04-13T10:25:34.310 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 823, in load_module
2018-04-13T10:25:34.310 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 682, in load_module
2018-04-13T10:25:34.311 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
2018-04-13T10:25:34.311 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 684, in _load
2018-04-13T10:25:34.311 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2018-04-13T10:25:34.311 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2018-04-13T10:25:34.311 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2018-04-13T10:25:34.311 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "/srv/modules/runners/proposal.py", line 18, in <module>
2018-04-13T10:25:34.311 INFO:teuthology.orchestra.run.target213032075235.stderr:    from deepsea_minions import DeepseaMinions
2018-04-13T10:25:34.311 INFO:teuthology.orchestra.run.target213032075235.stderr:ModuleNotFoundError: No module named 'deepsea_minions'
2018-04-13T10:25:34.315 INFO:teuthology.orchestra.run.target213032075235.stderr:[DEBUG   ] Failed to import runners validate:
2018-04-13T10:25:34.315 INFO:teuthology.orchestra.run.target213032075235.stderr:Traceback (most recent call last):
2018-04-13T10:25:34.316 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1452, in _load_module
2018-04-13T10:25:34.316 INFO:teuthology.orchestra.run.target213032075235.stderr:    mod = spec.loader.load_module()
2018-04-13T10:25:34.316 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
2018-04-13T10:25:34.316 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 823, in load_module
2018-04-13T10:25:34.316 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 682, in load_module
2018-04-13T10:25:34.316 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
2018-04-13T10:25:34.316 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 684, in _load
2018-04-13T10:25:34.316 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2018-04-13T10:25:34.317 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2018-04-13T10:25:34.317 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2018-04-13T10:25:34.317 INFO:teuthology.orchestra.run.target213032075235.stderr:  File "/srv/modules/runners/validate.py", line 34, in <module>
2018-04-13T10:25:34.317 INFO:teuthology.orchestra.run.target213032075235.stderr:    from deepsea_minions import DeepseaMinions
2018-04-13T10:25:34.317 INFO:teuthology.orchestra.run.target213032075235.stderr:ModuleNotFoundError: No module named 'deepsea_minions'
```

### Setup

today's DeepSea master branch, Salt 2018

### Steps to Reproduce Issue

Run Stages 0-3, and then `salt-run state.orch ceph.restart`

**Comment by smithfarm** [comment]
I forgot to blow away the `__pycache__` directory before running the orchestration.
