### ISSUE TITLE
state.orch ceph.stage.discovery failure

### ISSUE THREAD

**Issue by noelmcloughlin** [SUSE/DeepSea#1201]
### Description of Issue/Question

Command `sudo salt-run state.orch ceph.stage.discovery` has a failure. Need to investigate.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
$ sudo salt-run state.orch ceph.stage.discovery
[WARNING ] All minions are ready
[ERROR   ] {u'return': u'Exception occurred in runner populate.proposals: Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/srv/modules/runners/populate.py", line 911, in proposals\n    ceph_roles.cluster_config()\n  File "/srv/modules/runners/populate.py", line 615, in cluster_config\n    contents[\'fsid\'] = str(uuid.uuid3(uuid.NAMESPACE_DNS, random_string))\n  File "/usr/lib/python2.7/uuid.py", line 579, in uuid3\n    hash = md5(namespace.bytes + name).digest()\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xa7 in position 1: ordinal not in range(128)\n'}
[ERROR   ] Verify that targeted minions have proposal.generate
[ERROR   ] Verify that targeted minions have proposal.generate
[ERROR   ] Verify that targeted minions have proposal.generate
[ERROR   ] Verify that targeted minions have proposal.generate
[ERROR   ] Verify that targeted minions have proposal.generate
{}
masterminion_master:
  Name: minions.ready - Function: salt.runner - Result: Changed Started: - 20:24:24.926048 Duration: 671.55 ms
  Name: refresh_pillar0 - Function: salt.state - Result: Changed Started: - 20:24:25.597791 Duration: 651.256 ms
----------
          ID: discover roles
    Function: salt.runner
        Name: populate.proposals
      Result: False
     Comment: Runner function 'populate.proposals' failed.
     Started: 20:24:26.249558
    Duration: 3688.274 ms
     Changes:   
              ----------
              return:
                  Exception occurred in runner populate.proposals: Traceback (most recent call last):
                    File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
                      data['return'] = self.functions[fun](*args, **kwargs)
                    File "/srv/modules/runners/populate.py", line 911, in proposals
                      ceph_roles.cluster_config()
                    File "/srv/modules/runners/populate.py", line 615, in cluster_config
                      contents['fsid'] = str(uuid.uuid3(uuid.NAMESPACE_DNS, random_string))
                    File "/usr/lib/python2.7/uuid.py", line 579, in uuid3
                      hash = md5(namespace.bytes + name).digest()
                  UnicodeDecodeError: 'ascii' codec can't decode byte 0xa7 in position 1: ordinal not in range(128)
  Name: proposal.populate - Function: salt.runner - Result: Changed Started: - 20:24:29.938143 Duration: 1267.706 ms

Summary for masterminion_master
------------
Succeeded: 3 (changed=4)
Failed:    1
------------
Total states run:     4
Total run time:   6.279 s
```

### Versions Report

```
0.9.5+62.gac468eb

ii  salt-api                         2018.3.1+ds-1                           all          Generic, modular network access system
ii  salt-common                      2018.3.1+ds-1                           all          shared libraries that salt requires for all packages
ii  salt-master                      2018.3.1+ds-1                           all          remote manager to administer servers via salt
ii  salt-minion                      2018.3.1+ds-1                           all          client package for salt, the distributed remote execution system
```

**Comment by noelmcloughlin** [comment]
Here's how to REPLicate.
```
$ python
Python 2.7.13 (default, Apr  4 2017, 08:46:44) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from base64 import b64encode
>>> random_string = b64encode(os.urandom(64)).decode('utf-8')
>>> import uuid
>>> str(uuid.uuid3(uuid.NAMESPACE_DNS, random_string))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/uuid.py", line 579, in uuid3
    hash = md5(namespace.bytes + name).digest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa7 in position 1: ordinal not in range(128)
>>> str(uuid.uuid3(uuid.NAMESPACE_DNS, random_string))
```

**Comment by swiftgist** [comment]
Hmm, does `uuid.uuid4` work for you?  I just tried it and it looks okay.

**Comment by noelmcloughlin** [comment]
Yes, `uuid4()` returns a valid UUID making  `uuid.NAMESPACE` and `random_string` args are superfluous.  In PR #1202 I retained `uuid3(arg, arg)` which is one option.  Happy to get some advice.

The goal is to generate a UUID according to RFC4122. Here are some extracts.....

> The version 3 or 5 UUID is meant for generating UUIDs from "names"
>    that are drawn from, and unique within, some "name space".  The
>    concept of name and name space should be broadly construed, and not
>    limited to textual names.  For example, some name spaces are the
>    domain name system, URLs, ISO Object IDs (OIDs), X.500 Distinguished
>    Names (DNs), and reserved words in a programming language.  The
>    mechanisms or conventions used for allocating names and ensuring
>    their uniqueness within their name spaces are beyond the scope of
>    this specification.
> 

> The version 4 UUID is meant for generating UUIDs from truly-random or pseudo-random numbers.

There is no definition of "truly-random" number, but "pseudo-random" is defined:

> Identifier uniqueness considerations:
>       This document specifies three algorithms to generate UUIDs: the
>       first leverages the unique values of 802 MAC addresses to
>       guarantee uniqueness, the second uses pseudo-random number
>       generators, and the third uses cryptographic hashing and
>       application-provided text strings.  As a result, the UUIDs
>       generated according to the mechanisms here will be unique from all
>       other UUIDs that have been or will be assigned.
