### ISSUE TITLE
lint broken: AttributeError: module 'astroid.nodes' has no attribute 'Class'

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#1224]
As seen in automated testing of #1025, there's a problem with our lint setup:

````
GLOB sdist-make: /home/tserong/src/github/SUSE/DeepSea/setup.py
lint create: /home/tserong/src/github/SUSE/DeepSea/.tox/lint
lint installdeps: ipaddress, salt<2017.0.0, saltpylint
lint inst: /home/tserong/src/github/SUSE/DeepSea/.tox/dist/deepsea-0.9.5+75.g8c703c1d.zip
lint installed: astroid==2.0,certifi==2018.4.16,chardet==3.0.4,deepsea==0.9.5+75.g8c703c1d,idna==2.7,ipaddress==1.0.22,isort==4.3.4,Jinja2==2.10,lazy-object-proxy==1.3.1,MarkupSafe==1.0,mccabe==0.6.1,modernize==0.5,msgpack-python==0.5.6,pep8==1.6.2,pycrypto==2.6.1,pylint==2.0.0,PyYAML==3.13,pyzmq==17.1.0,requests==2.19.1,salt==2016.11.9,SaltPyLint==2017.12.15,six==1.11.0,tornado==5.1,typed-ast==1.1.0,urllib3==1.23,wrapt==1.10.11
lint runtests: PYTHONHASHSEED='1872628738'
lint runtests: commands[0] | pylint --rcfile=.pylintrc srv/
Traceback (most recent call last):
  File "/home/tserong/src/github/SUSE/DeepSea/.tox/lint/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/tserong/src/github/SUSE/DeepSea/.tox/lint/lib/python3.6/site-packages/pylint/__init__.py", line 19, in run_pylint
    Run(sys.argv[1:])
  File "/home/tserong/src/github/SUSE/DeepSea/.tox/lint/lib/python3.6/site-packages/pylint/lint.py", line 1359, in __init__
    linter.load_plugin_modules(plugins)
  File "/home/tserong/src/github/SUSE/DeepSea/.tox/lint/lib/python3.6/site-packages/pylint/lint.py", line 520, in load_plugin_modules
    module.register(self)
  File "/home/tserong/src/github/SUSE/DeepSea/.tox/lint/lib/python3.6/site-packages/saltpylint/smartup.py", line 43, in register
    MANAGER.register_transform(nodes.Class, rootlogger_transform)
AttributeError: module 'astroid.nodes' has no attribute 'Class'
ERROR: InvocationError: '/home/tserong/src/github/SUSE/DeepSea/.tox/lint/bin/pylint --rcfile=.pylintrc srv/'
````

This used to work just fine, but seems to have broken since pylint==2.0.0 appeared. If I force it back to pylint==1.9.2, it runs fine:

````
diff --git a/tox.ini b/tox.ini
index 6518e151..5b8a54aa 100644
--- a/tox.ini
+++ b/tox.ini
@@ -34,4 +34,5 @@ basepython = python3
 commands = pylint --rcfile=.pylintrc  srv/
 deps =
     {[base]deps}
+    pylint==1.9.2
     saltpylint
````

I don't know that forcing a particular pylint version is the really the right thing to do though...

**Comment by jschmid1** [comment]
right.. 3 days ago they released 2.0 ( https://pypi.org/project/pylint/#history ) 

I don't know if it's actually worth looking deeper into the root cause.. 

Is anyone totally against the workaround -OR- want to entangle the dependencies of pylint/saltpylint?

@alexandergraul @kbaikov

**Comment by alexandergraul** [comment]
pylint 1.9+ is [supported until 2020](http://pylint.pycqa.org/en/latest/whatsnew/2.0.html) (python2 end of life),  so I don't mind using that version.

 I suggest `pylint<2.0` instead of fixing it to `pylint==1.9.2` though, to have an easier time dealing with bugfix releases that are mentioned in the link above.

**Comment by jschmid1** [comment]
ok @alexandergraul so be it. would you mind pushinng a fix?
