### ISSUE TITLE
deepsea-cli fails with TypeError if deepsea_minions do not match

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#1231]
### Steps to Reproduce Issue

let /srv/pillar/ceph/deepsea_minions.sls point to a non-existent target e.g.

```yaml
deepsea_minions: 'nope*'
````

run stage.0

`deepsea stage run ceph.stage.0`

will result in this backtrace:

```
TypeError: unicode argument expected, got 'str'                                                                            [269/1873]
Traceback (most recent call last):                                                                                                   
  File "/usr/bin/deepsea", line 11, in <module>                                                                                      
    load_entry_point('deepsea==0.8.5+25.g16d4b99e9', 'console_scripts', 'deepsea')()                                                 
  File "/usr/lib/python2.7/site-packages/deepsea/deepsea.py", line 371, in main                                                      
    cli(prog_name='deepsea')                                                                                                         
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__                                                       
    return self.main(*args, **kwargs)                                                                                                
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main                                                           
    rv = self.invoke(ctx)                                                                                                            
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke                                                        
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                          
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke                                                        
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                          
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke                                                             return ctx.invoke(self.callback, **ctx.params)                                                                                   
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke                                                         
    return callback(*args, **kwargs)                                                                                                 
  File "/usr/lib/python2.7/site-packages/deepsea/common.py", line 66, in func_wraper                                                 
    return func(*args, **kwargs)                                                                                                     
  File "/usr/lib/python2.7/site-packages/deepsea/deepsea.py", line 326, in stage_run                                                 
    ret = run_stage(stage_name, hide_state_steps, hide_dynamic_steps, simple_output)                                                 
  File "/usr/lib/python2.7/site-packages/deepsea/stage_executor.py", line 79, in run_stage                                           
    mon.parse_stage(stage_name)
  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 533, in parse_stage
    self._monitor_listeners)
  File "/usr/lib/python2.7/site-packages/deepsea/stage_parser.py", line 295, in parse_stage
    res, _, _ = SLSRenderer.render(list(states), target)
  File "/usr/lib/python2.7/site-packages/deepsea/stage_parser.py", line 136, in render
    return cls._render_in_minion(state_name, target)
  File "/usr/lib/python2.7/site-packages/deepsea/stage_parser.py", line 153, in _render_in_minion
    state_name, expr_form="compound")
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 655, in cmd
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 337, in run_job
    return self._check_pub_data(pub_data)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 279, in _check_pub_data
    print('No minions matched the target. '
TypeError: unicode argument expected, got 'str'

```

**Comment by rjfd** [comment]
@jschmid1 that looks like a bug inside Salt, because the exception is being raised inside the salt python library.

**Comment by jschmid1** [comment]
> @jschmid1 that looks like a bug inside Salt, because the exception is being raised inside the salt python library.

 you are right.. so unfortunately we can't do anything about that. Which is a bit unfortunate because we have a validation test for this exact situation. The reason we don't see this failing is the suppression of stdout? @rjfd

**Comment by rjfd** [comment]
> The reason we don't see this failing is the suppression of stdout?

Yes, most likely. But how did you get that stacktrace?

**Comment by jschmid1** [comment]
from the minion logs @rjfd

**Comment by rjfd** [comment]
@jschmid1 no news. Can you tell me the steps to reproduce this issue? I'm not able to reproduce and because of that it's hard to come up with a fix.

**Comment by jschmid1** [comment]
@rjfd doesn't the reproducer steps in the description work for you?
