### ISSUE TITLE
No module named six.moves

### ISSUE THREAD

**Issue by hemna** [SUSE/DeepSea#1306]
Installed from vagrant-ceph and when I run deepsea salt-run I get a failure.

```
vagrant@admin:~> sudo deepsea salt-run
Traceback (most recent call last):
  File "/usr/bin/deepsea", line 9, in <module>
    load_entry_point('deepsea==0.8.5', 'console_scripts', 'deepsea')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/deepsea/__main__.py", line 10, in <module>
    from .deepsea import main
  File "/usr/lib/python2.7/site-packages/deepsea/deepsea.py", line 22, in <module>
    from .monitor import Monitor
  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 14, in <module>
    from six.moves import range
ImportError: No module named six.moves
```

**Comment by jschmid1** [comment]
fixed by #1290
