### ISSUE TITLE
Stage 4 fails to deploy openATTIC on OpenStack VMs (lrbd.service fails to start, "mount: none is already mounted or /sys/kernel/config busy")

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#1315]
### Description of Issue/Question

3-node cluster in OVH, SES5 on out-of-date SLE-12-SP3, with the following policy.cfg:

```
2018-08-24T14:55:23.365 INFO:teuthology.orchestra.run.target167114251083.stdout:# Cluster assignment
2018-08-24T14:55:23.365 INFO:teuthology.orchestra.run.target167114251083.stdout:cluster-ceph/cluster/*.sls
2018-08-24T14:55:23.365 INFO:teuthology.orchestra.run.target167114251083.stdout:# Common configuration
2018-08-24T14:55:23.365 INFO:teuthology.orchestra.run.target167114251083.stdout:config/stack/default/global.yml
2018-08-24T14:55:23.365 INFO:teuthology.orchestra.run.target167114251083.stdout:config/stack/default/ceph/cluster.yml
2018-08-24T14:55:23.365 INFO:teuthology.orchestra.run.target167114251083.stdout:# Role assignment - master
2018-08-24T14:55:23.366 INFO:teuthology.orchestra.run.target167114251083.stdout:role-master/cluster/target167114251083.teuthology.sls
2018-08-24T14:55:23.366 INFO:teuthology.orchestra.run.target167114251083.stdout:# Role assignment - admin
2018-08-24T14:55:23.366 INFO:teuthology.orchestra.run.target167114251083.stdout:role-admin/cluster/*.sls
2018-08-24T14:55:23.366 INFO:teuthology.orchestra.run.target167114251083.stdout:# Role assignment - 1 mon, 1 mgr
2018-08-24T14:55:23.366 INFO:teuthology.orchestra.run.target167114251083.stdout:role-mon/cluster/*.sls slice=[:1]
2018-08-24T14:55:23.366 INFO:teuthology.orchestra.run.target167114251083.stdout:role-mgr/cluster/*.sls slice=[:1]
2018-08-24T14:55:23.367 INFO:teuthology.orchestra.run.target167114251083.stdout:# Role assignment - mds
2018-08-24T14:55:23.367 INFO:teuthology.orchestra.run.target167114251083.stdout:role-mds/cluster/*.sls slice=[:2]
2018-08-24T14:55:23.367 INFO:teuthology.orchestra.run.target167114251083.stdout:# Role assignment - openattic
2018-08-24T14:55:23.367 INFO:teuthology.orchestra.run.target167114251083.stdout:role-openattic/cluster/*.sls slice=[:1]
2018-08-24T14:55:23.367 INFO:teuthology.orchestra.run.target167114251083.stdout:# Role assignment - rgw
2018-08-24T14:55:23.368 INFO:teuthology.orchestra.run.target167114251083.stdout:role-rgw/cluster/*.sls slice=[1:2]
2018-08-24T14:55:23.368 INFO:teuthology.orchestra.run.target167114251083.stdout:# Role assignment - igw
2018-08-24T14:55:23.368 INFO:teuthology.orchestra.run.target167114251083.stdout:role-igw/cluster/*.sls slice=[1:2]
2018-08-24T14:55:23.368 INFO:teuthology.orchestra.run.target167114251083.stdout:# Role assignment - ganesha
2018-08-24T14:55:23.368 INFO:teuthology.orchestra.run.target167114251083.stdout:role-ganesha/cluster/*.sls slice=[1:2]
2018-08-24T14:55:23.369 INFO:teuthology.orchestra.run.target167114251083.stdout:# Hardware Profile
2018-08-24T14:55:23.370 INFO:teuthology.orchestra.run.target167114251083.stdout:profile-default/cluster/*.sls slice=[:-1]
2018-08-24T14:55:23.370 INFO:teuthology.orchestra.run.target167114251083.stdout:profile-default/stack/default/ceph/minions/*yml slice=[:-1]
2018-08-24T14:55:23.370 INFO:teuthology.orchestra.run.target167114251083.stdout:
```

(i.e. all possible roles deployed, including openattic)

Stage 4 fails transiently like so:

```
2018-08-24T15:01:11.654 INFO:teuthology.orchestra.run.target167114251083.stderr:+ timeout 30m deepsea --log-file=/var/log/salt/deepsea.log --log-level=debug stage run ceph.stage.4 --simple-output
2018-08-24T15:01:11.971 INFO:teuthology.orchestra.run.target167114251083.stdout:Starting stage: ceph.stage.4
2018-08-24T15:02:57.684 INFO:teuthology.orchestra.run.target167114251083.stdout:Parsing stage ceph.stage.4 steps... done
2018-08-24T15:02:57.684 INFO:teuthology.orchestra.run.target167114251083.stdout:
2018-08-24T15:02:57.684 INFO:teuthology.orchestra.run.target167114251083.stdout:Stage initialization output:
2018-08-24T15:02:57.685 INFO:teuthology.orchestra.run.target167114251083.stdout:
2018-08-24T15:02:57.685 INFO:teuthology.orchestra.run.target167114251083.stdout:
2018-08-24T15:02:57.685 INFO:teuthology.orchestra.run.target167114251083.stdout:[init] Executing runner validate.deploy... ok
2018-08-24T15:02:57.685 INFO:teuthology.orchestra.run.target167114251083.stdout:[init] Executing runner select.minions... ok
2018-08-24T15:02:57.685 INFO:teuthology.orchestra.run.target167114251083.stdout:[init] Executing runner select.one_minion... ok
2018-08-24T15:02:57.685 INFO:teuthology.orchestra.run.target167114251083.stdout:[init] Executing runner select.minions... ok
2018-08-24T15:02:57.685 INFO:teuthology.orchestra.run.target167114251083.stdout:[init] Executing runner cephprocesses.need_restart_config_change... ok
2018-08-24T15:02:57.685 INFO:teuthology.orchestra.run.target167114251083.stdout:[init] Executing runner cephprocesses.need_restart_lsof...
2018-08-24T15:02:57.685 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  cephprocesses.need_restart_lsof(role=mds)...
2018-08-24T15:02:57.686 INFO:teuthology.orchestra.run.target167114251083.stdout:               in target167114251009.teuthology... ok
2018-08-24T15:02:57.686 INFO:teuthology.orchestra.run.target167114251083.stdout:               in target167114251083.teuthology... ok
2018-08-24T15:02:57.686 INFO:teuthology.orchestra.run.target167114251083.stdout:[init] Executing runner cephprocesses.need_restart_lsof... ok
2018-08-24T15:02:57.686 INFO:teuthology.orchestra.run.target167114251083.stdout:[init] Executing runner select.minions... ok
2018-08-24T15:02:57.686 INFO:teuthology.orchestra.run.target167114251083.stdout:[init] Executing runner select.minions... ok
2018-08-24T15:02:57.686 INFO:teuthology.orchestra.run.target167114251083.stdout:[init] Executing runner select.minions... ok
2018-08-24T15:02:57.686 INFO:teuthology.orchestra.run.target167114251083.stdout:[init] Executing runner sharedsecret.show... ok
2018-08-24T15:02:57.686 INFO:teuthology.orchestra.run.target167114251083.stdout:
2018-08-24T15:02:57.692 INFO:teuthology.orchestra.run.target167114251083.stdout:[1/34] Executing state mine.send...
2018-08-24T15:02:57.692 INFO:teuthology.orchestra.run.target167114251083.stdout:         target167114251083.teuthology... ok
2018-08-24T15:02:57.692 INFO:teuthology.orchestra.run.target167114251083.stdout:[2/34] Executing state ceph.igw.config...
2018-08-24T15:02:57.693 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  select.minions(cluster=ceph, roles=igw)... ok
2018-08-24T15:02:57.693 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  target167114251083.teuthology: demo pool(ceph osd pool create iscsi-images 128) ok
2018-08-24T15:02:57.693 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  target167114251083.teuthology: demo pool enable application(ceph osd pool application enable iscsi-images rbd || :) ok
2018-08-24T15:02:57.693 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  target167114251083.teuthology: demo image(rbd -p iscsi-images create demo --size=1024) ok
2018-08-24T15:02:57.693 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  select.minions(cluster=ceph, roles=igw)... ok
2018-08-24T15:02:57.693 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  select.public_addresses(cluster=ceph, tuples=True, roles=igw)...
2018-08-24T15:02:57.693 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  public.address()...
2018-08-24T15:02:57.693 INFO:teuthology.orchestra.run.target167114251083.stdout:               in target167114251083.teuthology... ok
2018-08-24T15:02:57.693 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  select.public_addresses(cluster=ceph, tuples=True, roles=igw)... ok
2018-08-24T15:02:57.694 INFO:teuthology.orchestra.run.target167114251083.stdout:         target167114251083.teuthology... ok
2018-08-24T15:02:57.694 INFO:teuthology.orchestra.run.target167114251083.stdout:[3/34] Executing state ceph.igw.auth...
2018-08-24T15:02:57.694 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  select.minions(cluster=ceph, host=True, roles=igw)... ok
2018-08-24T15:02:57.694 INFO:teuthology.orchestra.run.target167114251083.stdout:         target167114251083.teuthology... ok
2018-08-24T15:02:57.694 INFO:teuthology.orchestra.run.target167114251083.stdout:[4/34] Executing state ceph.igw.keyring...
2018-08-24T15:02:57.694 INFO:teuthology.orchestra.run.target167114251083.stdout:         target167114251083.teuthology... ok
2018-08-24T15:02:57.694 INFO:teuthology.orchestra.run.target167114251083.stdout:[5/34] Executing state ceph.igw.sysconfig...
2018-08-24T15:02:57.694 INFO:teuthology.orchestra.run.target167114251083.stdout:         target167114251083.teuthology... ok
2018-08-24T15:02:57.694 INFO:teuthology.orchestra.run.target167114251083.stdout:[6/34] Executing state ceph.igw.import...
2018-08-24T15:02:57.694 INFO:teuthology.orchestra.run.target167114251083.stdout:         target167114251083.teuthology... ok
2018-08-24T15:02:57.707 INFO:teuthology.orchestra.run.target167114251083.stdout:[7/34] Executing state ceph.igw...
2018-08-24T15:02:57.707 INFO:teuthology.orchestra.run.target167114251083.stdout:         target167114251083.teuthology... fail
2018-08-24T15:02:57.707 INFO:teuthology.orchestra.run.target167114251083.stdout:[8/34] Executing state ceph.wait...
2018-08-24T15:02:57.707 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  target167114251083.teuthology: wait(wait.out) ok
2018-08-24T15:02:57.707 INFO:teuthology.orchestra.run.target167114251083.stdout:         target167114251083.teuthology... ok
2018-08-24T15:02:57.707 INFO:teuthology.orchestra.run.target167114251083.stdout:[9/34] Executing state ceph.processes.igw...
2018-08-24T15:02:57.707 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  target167114251083.teuthology: wait for igw processes(cephprocesses.wait) ok
2018-08-24T15:02:57.708 INFO:teuthology.orchestra.run.target167114251083.stdout:         target167114251083.teuthology... ok
2018-08-24T15:02:57.708 INFO:teuthology.orchestra.run.target167114251083.stdout:[10/34] Executing state ceph.igw.restart...
2018-08-24T15:02:57.708 INFO:teuthology.orchestra.run.target167114251083.stdout:         |_  target167114251083.teuthology: restart(systemctl reload lrbd) fail
2018-08-24T15:02:57.708 INFO:teuthology.orchestra.run.target167114251083.stdout:         target167114251083.teuthology... fail
2018-08-24T15:02:57.708 INFO:teuthology.orchestra.run.target167114251083.stdout:Finished stage ceph.stage.4: succeeded=8/34 failed=2/34
2018-08-24T15:02:57.708 INFO:teuthology.orchestra.run.target167114251083.stdout:
2018-08-24T15:02:57.708 INFO:teuthology.orchestra.run.target167114251083.stdout:Failures summary:
2018-08-24T15:02:57.708 INFO:teuthology.orchestra.run.target167114251083.stdout:ceph.igw (/srv/salt/ceph/igw):
2018-08-24T15:02:57.708 INFO:teuthology.orchestra.run.target167114251083.stdout:  target167114251083.teuthology:
2018-08-24T15:02:57.709 INFO:teuthology.orchestra.run.target167114251083.stdout:    enable lrbd: Service lrbd has been enabled, and is dead
2018-08-24T15:02:57.709 INFO:teuthology.orchestra.run.target167114251083.stdout:ceph.igw.restart (/srv/salt/ceph/igw/restart):
2018-08-24T15:02:57.709 INFO:teuthology.orchestra.run.target167114251083.stdout:  target167114251083.teuthology:
2018-08-24T15:02:57.709 INFO:teuthology.orchestra.run.target167114251083.stdout:    restart: Command "systemctl reload lrbd" run
2018-08-24T15:02:57.709 INFO:teuthology.orchestra.run.target167114251083.stdout:        stdout:
2018-08-24T15:02:57.709 INFO:teuthology.orchestra.run.target167114251083.stdout:        stderr: Job for lrbd.service invalid.
2018-08-24T15:02:57.723 INFO:teuthology.orchestra.run.target167114251083.stdout:deepsea exit status: 1
```

I believe the Stage 4 failure happens because lrbd.service fails to start. When I look in journalctl after Stage 4 fails, I see the following lrbd traceback (CAVEAT: the lines are in reverse chronological order!)

```
2018-08-24T15:02:58.977 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology systemd[1]: lrbd.service: Failed with result 'exit-code'.
2018-08-24T15:02:58.977 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology systemd[1]: lrbd.service: Unit entered failed state.
2018-08-24T15:02:58.977 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology systemd[1]: Failed to start configures target.service from Ceph.
2018-08-24T15:02:58.977 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology systemd[1]: lrbd.service: Main process exited, code=exited, status=1/FAILURE
2018-08-24T15:02:58.977 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]: TypeError: expected a string or other character buffer object
2018-08-24T15:02:58.977 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:     self._stdout.write(text)
2018-08-24T15:02:58.977 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:   File "/usr/lib/python2.7/site-packages/configshell/console.py", line 141, in raw_write
2018-08-24T15:02:58.977 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:     self.raw_write(text)
2018-08-24T15:02:58.977 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:   File "/usr/lib/python2.7/site-packages/configshell/console.py", line 153, in display
2018-08-24T15:02:58.978 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:     self.con.display(msg)
2018-08-24T15:02:58.978 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:   File "/usr/lib/python2.7/site-packages/configshell/log.py", line 112, in _log
2018-08-24T15:02:58.979 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:     self._log('error', msg)
2018-08-24T15:02:59.027 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:   File "/usr/lib/python2.7/site-packages/configshell/log.py", line 159, in error
2018-08-24T15:02:59.028 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:     self.log.error(msg)
2018-08-24T15:02:59.028 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:   File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 899, in _execute_command
2018-08-24T15:02:59.028 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:     self._execute_command(path, command, pparams, kparams)
2018-08-24T15:02:59.029 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:   File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 934, in run_cmdline
2018-08-24T15:02:59.029 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:     shell.run_cmdline(" ".join(sys.argv[1:]))
2018-08-24T15:02:59.030 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:   File "/usr/bin/targetcli", line 71, in main
2018-08-24T15:02:59.030 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:     main()
2018-08-24T15:02:59.030 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]:   File "/usr/bin/targetcli", line 82, in <module>
2018-08-24T15:02:59.030 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]: Traceback (most recent call last):
2018-08-24T15:02:59.030 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]: mount: none is already mounted or /sys/kernel/config busy
2018-08-24T15:02:59.030 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]: Warning: Could not load preferences file /root/.targetcli/prefs.bin.
2018-08-24T15:02:59.030 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]: targetcli /backstores/rbd create name=iscsi-images-demo dev=/dev/rbd/iscsi-images/demo
2018-08-24T15:02:59.030 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]: /dev/rbd0
2018-08-24T15:02:59.031 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]: rbd -p iscsi-images --name client.igw.target167114251083 map demo
2018-08-24T15:02:59.050 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology lrbd[38492]: ERROR: command failed
2018-08-24T15:02:59.050 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology systemd[1]: Mounted Configuration File System.
2018-08-24T15:02:59.050 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology systemd[1]: Mounting Configuration File System...
2018-08-24T15:02:59.050 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology kernel: Rounding down aligned max_sectors from 4294967295 to 4294967288
2018-08-24T15:02:59.050 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology kernel: rbd: rbd0: capacity 1073741824 features 0x1
2018-08-24T15:02:59.050 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology kernel: libceph: client14135 fsid 0bd1ee35-3cac-3b31-8bef-1fbb0d5767db
2018-08-24T15:02:59.059 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology kernel: libceph: mon0 167.114.251.9:6789 session established
2018-08-24T15:02:59.059 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology kernel: rbd: loaded (major 252)
2018-08-24T15:02:59.059 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology kernel: libceph: loaded (mon/osd proto 15/24)
2018-08-24T15:02:59.059 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology kernel: Key type ceph registered
2018-08-24T15:02:59.059 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology systemd[1]: Starting configures target.service from Ceph...
2018-08-24T15:02:59.060 INFO:teuthology.orchestra.run.target167114251083.stdout:Aug 24 15:02:48 target167114251083.teuthology systemd[1]: Started /usr/bin/systemctl start lrbd.service.
```

Full log: http://158.69.90.90:8080/job/deepsea-pr/84/testReport/junit/teuthology.suse/tier1/suse_tier1_openattic__cluster_3nodes2disks_yaml_distros_sle_12_3_yaml_exec_health_openattic_cli_yaml_tasks_yaml_/attachments/teuthology-2938.log

One last note: deploying a cluster with igw role works fine. Even deploying a cluster with all roles except openattic works. The failure happens when the openattic role is added.

Versions:

deepsea 0.8.5+91.gffe84290 (PR #1289)
lrbd-1.5-1.2.noarch.rpm
openattic-3.7.0~201806180933-1.11.noarch.rpm

Salt:

```
2018-08-24T14:51:46.838 INFO:teuthology.orchestra.run.target167114251083.stdout:    Forcing installation of 'salt-master-2016.11.4-48.6.8.x86_64' from repository 'ceph_repo5'.
2018-08-24T14:51:46.838 INFO:teuthology.orchestra.run.target167114251083.stdout:    Forcing installation of 'salt-2016.11.4-48.6.8.x86_64' from repository 'ceph_repo5'.
2018-08-24T14:51:46.838 INFO:teuthology.orchestra.run.target167114251083.stdout:    Forcing installation of 'salt-api-2016.11.4-48.6.8.x86_64' from repository 'ceph_repo5'.
2018-08-24T14:51:46.839 INFO:teuthology.orchestra.run.target167114251083.stdout:    Forcing installation of 'salt-minion-2016.11.4-48.6.8.x86_64' from repository 'ceph_repo5'.
```

**Comment by smithfarm** [comment]
Could it be the version of lrbd (1.5) is old?

**Comment by smithfarm** [comment]
What's odd here is that igw deployment works fine. The error happens only when openattic role is added to the mix.

**Comment by smithfarm** [comment]
Removed the word "reproducibly" from the title because the reproducibility is in question.

**Comment by smithfarm** [comment]
Reproduced on ECP here: https://ci.suse.de/job/storage-qa-teuthology-smoke-devel-5.0/lastCompletedBuild/testReport/teuthology/Devel/suse_tier1_openattic__cluster_3nodes2disks_yaml_distros_sle_12_3_yaml_exec_health_openattic_cli_yaml_tasks_yaml_/attachments/teuthology-suse%3Atier1-158.log

**Comment by smithfarm** [comment]
I have seen this happen in both OVH and ECP, but only when deepsea is installed from RPM.

I tried, but failed, to reproduce it in my own teuthology env - the only difference would seem to be that the latter env installs deepsea from source.

**Comment by smithfarm** [comment]
No longer seeing this so often. Now seeing #1385 which might be related?

**Comment by smithfarm** [comment]
Have not seen this since updating the underlying OS image.
