### ISSUE TITLE
Stage 5 not compatible with deepsea CLI

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#1364]
### Description of Issue/Question

On latest SES5:

```
2018-09-06T21:03:08.045 INFO:teuthology.orchestra.run.target149202176243.stdout:*********************************************
2018-09-06T21:03:08.045 INFO:teuthology.orchestra.run.target149202176243.stdout:********** Running DeepSea Stage 5 **********
2018-09-06T21:03:08.045 INFO:teuthology.orchestra.run.target149202176243.stdout:*********************************************
2018-09-06T21:03:08.045 INFO:teuthology.orchestra.run.target149202176243.stderr:+ run_stage_5 --cli
2018-09-06T21:03:08.045 INFO:teuthology.orchestra.run.target149202176243.stderr:+ _run_stage 5 --cli
2018-09-06T21:03:08.045 INFO:teuthology.orchestra.run.target149202176243.stderr:+ local stage_num=5
2018-09-06T21:03:08.046 INFO:teuthology.orchestra.run.target149202176243.stderr:+ set +x
2018-09-06T21:03:08.046 INFO:teuthology.orchestra.run.target149202176243.stderr:+ tee /tmp/deepsea.5.log
2018-09-06T21:03:08.046 INFO:teuthology.orchestra.run.target149202176243.stderr:+ timeout 60m deepsea --log-file=/var/log/salt/deepsea.log --log-level=debug stage run ceph.stage.5 --simple-output
2018-09-06T21:03:08.361 INFO:teuthology.orchestra.run.target149202176243.stdout:Starting stage: ceph.stage.5
2018-09-06T21:03:34.581 INFO:teuthology.orchestra.run.target149202176243.stdout:Parsing stage ceph.stage.5 steps... Traceback (most recent call last):
2018-09-06T21:03:34.583 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/bin/deepsea", line 9, in <module>
2018-09-06T21:03:34.583 INFO:teuthology.orchestra.run.target149202176243.stdout:    load_entry_point('deepsea==0.0.0', 'console_scripts', 'deepsea')()
2018-09-06T21:03:34.583 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/deepsea/deepsea.py", line 371, in main
2018-09-06T21:03:34.583 INFO:teuthology.orchestra.run.target149202176243.stdout:    cli(prog_name='deepsea')
2018-09-06T21:03:34.584 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
2018-09-06T21:03:34.584 INFO:teuthology.orchestra.run.target149202176243.stdout:    return self.main(*args, **kwargs)
2018-09-06T21:03:34.584 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
2018-09-06T21:03:34.584 INFO:teuthology.orchestra.run.target149202176243.stdout:    rv = self.invoke(ctx)
2018-09-06T21:03:34.585 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
2018-09-06T21:03:34.585 INFO:teuthology.orchestra.run.target149202176243.stdout:    return _process_result(sub_ctx.command.invoke(sub_ctx))
2018-09-06T21:03:34.585 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
2018-09-06T21:03:34.586 INFO:teuthology.orchestra.run.target149202176243.stdout:    return _process_result(sub_ctx.command.invoke(sub_ctx))
2018-09-06T21:03:34.586 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
2018-09-06T21:03:34.587 INFO:teuthology.orchestra.run.target149202176243.stdout:    return ctx.invoke(self.callback, **ctx.params)
2018-09-06T21:03:34.587 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
2018-09-06T21:03:34.587 INFO:teuthology.orchestra.run.target149202176243.stdout:    return callback(*args, **kwargs)
2018-09-06T21:03:34.587 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/deepsea/common.py", line 66, in func_wraper
2018-09-06T21:03:34.588 INFO:teuthology.orchestra.run.target149202176243.stdout:    return func(*args, **kwargs)
2018-09-06T21:03:34.588 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/deepsea/deepsea.py", line 326, in stage_run
2018-09-06T21:03:34.588 INFO:teuthology.orchestra.run.target149202176243.stdout:    ret = run_stage(stage_name, hide_state_steps, hide_dynamic_steps, simple_output)
2018-09-06T21:03:34.588 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/deepsea/stage_executor.py", line 79, in run_stage
2018-09-06T21:03:34.588 INFO:teuthology.orchestra.run.target149202176243.stdout:    mon.parse_stage(stage_name)
2018-09-06T21:03:34.589 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 536, in parse_stage
2018-09-06T21:03:34.589 INFO:teuthology.orchestra.run.target149202176243.stdout:    self._monitor_listeners)
2018-09-06T21:03:34.589 INFO:teuthology.orchestra.run.target149202176243.stdout:  File "/usr/lib/python2.7/site-packages/deepsea/stage_parser.py", line 321, in parse_stage
2018-09-06T21:03:34.589 INFO:teuthology.orchestra.run.target149202176243.stdout:    if s_step and (not only_visible_steps or s_step.visible):
2018-09-06T21:03:34.590 INFO:teuthology.orchestra.run.target149202176243.stdout:AttributeError: 'SaltRunner' object has no attribute 'visible'
2018-09-06T21:03:34.616 INFO:teuthology.orchestra.run.target149202176243.stdout:deepsea exit status: 1
2018-09-06T21:03:34.617 INFO:teuthology.orchestra.run.target149202176243.stdout:WWWW
2018-09-06T21:03:34.617 INFO:teuthology.orchestra.run.target149202176243.stdout:********** Stage 5 failed **********
```

Reproducibility: unknown, but assumed to be reproducible

**Comment by smithfarm** [comment]
@rjfd Looks like problem is originating from this line:

```
f735e7764 (Ricardo Dias  2018-09-05 08:30:01 +0100 321)                         if s_step and (not only_visible_steps or s_step.visible):
f735e7764 (Ricardo Dias  2018-09-05 08:30:01 +0100 322)                             step.steps[minion].append(s_step)
```

I'm not 100% sure, but I believe the deepsea CLI was running Stage 5 OK before that commit went in.
