### ISSUE TITLE
TypeError: unhashable type: 'list' when running Stage 0 and Stage 4

### ISSUE THREAD

**Issue by squarejester** [SUSE/DeepSea#1407]
Starting today whenever I run stage 0 or stage 4 I get this exact same error message from both stages. I do not have any issues runnining stages 1,2,3, or 5. This is on openSUSE Leap 15.

Starting stage: ceph.stage.0
Parsing ceph.stage.0 steps... ?

[parsing] on master
            |_ ceph.stage.0

Traceback (most recent call last):
  File "/usr/bin/deepsea", line 11, in <module>
    load_entry_point('deepsea==0.9.6+git.0.86a614d3', 'console_scripts', 'deepsea')()
  File "/usr/lib/python3.6/site-packages/deepsea/deepsea.py", line 371, in main
    cli(prog_name='deepsea')
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/deepsea/common.py", line 66, in func_wraper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/deepsea/deepsea.py", line 326, in stage_run
    ret = run_stage(stage_name, hide_state_steps, hide_dynamic_steps, simple_output)
  File "/usr/lib/python3.6/site-packages/deepsea/stage_executor.py", line 79, in run_stage
    mon.parse_stage(stage_name)
  File "/usr/lib/python3.6/site-packages/deepsea/monitor.py", line 533, in parse_stage
    self._monitor_listeners)
  File "/usr/lib/python3.6/site-packages/deepsea/stage_parser.py", line 292, in parse_stage
    states_to_render[step.target[0]].add(step.sls)
TypeError: unhashable type: 'list'

**Comment by squarejester** [comment]
Ok. I think this should be left up in case others run into the same issue. The answer was very simple. I made sure all the servers used the same NTP server and rebooted the entire environment. Once I did that everything worked again without any issues.
