### ISSUE TITLE
Stage 4 fails in PR CI because "deepsea" repo cannot be refreshed

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#1438]
### Description of Issue/Question

In the PR CI (for PRs targeting master), Stage 4 recently started to reproducibly fail like this:

```
2018-10-26T19:18:28.021 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:----------
2018-10-26T19:18:28.021 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:          ID: setup prometheus rgw exporter
2018-10-26T19:18:28.021 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:    Function: salt.state
2018-10-26T19:18:28.022 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:      Result: False
2018-10-26T19:18:28.022 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:     Comment: Run failed on minions: target158069066078.teuthology
2018-10-26T19:18:28.022 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:     Started: 19:17:56.802165
2018-10-26T19:18:28.022 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:    Duration: 12452.159 ms
2018-10-26T19:18:28.023 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:     Changes:
2018-10-26T19:18:28.023 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:              target158069066078.teuthology:
2018-10-26T19:18:28.023 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:              ----------
2018-10-26T19:18:28.023 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                        ID: install_package
2018-10-26T19:18:28.023 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                  Function: pkg.installed
2018-10-26T19:18:28.024 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                      Name: python3-prometheus-client
2018-10-26T19:18:28.024 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                    Result: False
2018-10-26T19:18:28.024 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                   Comment: An exception occurred in this state: Traceback (most recent call last):
2018-10-26T19:18:28.024 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                              File "/usr/lib/python3.6/site-packages/salt/state.py", line 1878, in call
2018-10-26T19:18:28.024 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                                **cdata['kwargs'])
2018-10-26T19:18:28.025 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                              File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1823, in wrapper
2018-10-26T19:18:28.025 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                                return f(*args, **kwargs)
2018-10-26T19:18:28.025 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                              File "/usr/lib/python3.6/site-packages/salt/states/pkg.py", line 1487, in installed
2018-10-26T19:18:28.025 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                                pkgs, refresh = _resolve_capabilities(pkgs, refresh=refresh, **kwargs)
2018-10-26T19:18:28.025 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                              File "/usr/lib/python3.6/site-packages/salt/states/pkg.py", line 899, in _resolve_capabilities
2018-10-26T19:18:28.026 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                                ret = __salt__['pkg.resolve_capabilities'](pkgs, refresh=refresh, **kwargs)
2018-10-26T19:18:28.026 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                              File "/usr/lib/python3.6/site-packages/salt/modules/zypper.py", line 2235, in resolve_capabilities
2018-10-26T19:18:28.026 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                                refresh_db()
2018-10-26T19:18:28.026 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                              File "/usr/lib/python3.6/site-packages/salt/modules/zypper.py", line 1014, in refresh_db
2018-10-26T19:18:28.026 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                                out = __zypper__.refreshable.call('refresh', '--force')
2018-10-26T19:18:28.026 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                              File "/usr/lib/python3.6/site-packages/salt/modules/zypper.py", line 311, in __call
2018-10-26T19:18:28.026 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                                raise CommandExecutionError('Zypper command failure: {0}'.format(self.error_msg))
2018-10-26T19:18:28.026 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                            salt.exceptions.CommandExecutionError: Zypper command failure: Repository 'deepsea' is invalid.
2018-10-26T19:18:28.027 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                            [deepsea|http://ceph-ci.suse.de/artifacts/jenkins/deepsea-pr/suse:tier1/280] Valid metadata not found at specified URL
2018-10-26T19:18:28.027 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                            Please check if the URIs defined for this repository are pointing to a valid repository.
2018-10-26T19:18:28.027 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                            Skipping repository 'deepsea' because of the above error.
2018-10-26T19:18:28.027 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                            Some of the repositories have not been refreshed because of an error.
2018-10-26T19:18:28.027 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                   Started: 19:18:04.974949
2018-10-26T19:18:28.027 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                  Duration: 3651.731 ms
2018-10-26T19:18:28.027 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                   Changes:
2018-10-26T19:18:28.027 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                Name: /var/lib/prometheus/node-exporter/ceph_rgw.py - Function: file.managed - Result: Changed Started: - 19:18:08.630235 Duration: 112.047 ms
2018-10-26T19:18:28.028 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                Name: remove_rgw_exporter_cron_job - Function: cron.absent - Result: Clean Started: - 19:18:08.753495 Duration: 170.488 ms
2018-10-26T19:18:28.028 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:                Name: /var/lib/prometheus/node-exporter/ceph_rgw.py > /var/lib/prometheus/node-exporter/ceph_rgw.prom 2> /dev/null - Function: cron.present - Result: Changed Started: - 19:18:08.924377 Duration: 316.475 ms
2018-10-26T19:18:28.028 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:
2018-10-26T19:18:28.028 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:              Summary for target158069066078.teuthology
2018-10-26T19:18:28.028 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:              ------------
2018-10-26T19:18:28.029 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:              Succeeded: 3 (changed=2)
2018-10-26T19:18:28.029 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:              Failed:    1
2018-10-26T19:18:28.029 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:              ------------
2018-10-26T19:18:28.029 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:              Total states run:     4
2018-10-26T19:18:28.029 INFO:tasks.workunit.client.salt_master.target158069066078.stdout:              Total run time:   4.251 s
```

In other words, Salt's zypper module is trying to refresh the `deepsea` repo (http://ceph-ci.suse.de/artifacts/jenkins/deepsea-pr/suse:tier1/280/) and fails because zypper reports the repository is invalid.

### Setup

It happens in the PR CI only. The same repo is successfully refreshed at the start of the test (before Stage 0):

```
2018-10-26T19:49:40.940 INFO:tasks.workunit.client.salt_master.target158069067036.stdout:Installing dependencies on the Salt Master node
2018-10-26T19:49:42.064 INFO:tasks.workunit.client.salt_master.target158069067036.stdout:Repository 'basesystem' is up to date.
2018-10-26T19:49:42.087 INFO:tasks.workunit.client.salt_master.target158069067036.stdout:Repository 'deepsea' is up to date.
2018-10-26T19:49:42.093 INFO:tasks.workunit.client.salt_master.target158069067036.stdout:Repository 'internal' is up to date.
2018-10-26T19:49:42.099 INFO:tasks.workunit.client.salt_master.target158069067036.stdout:Repository 'server' is up to date.
2018-10-26T19:49:42.107 INFO:tasks.workunit.client.salt_master.target158069067036.stdout:Repository 'ses' is up to date.
2018-10-26T19:49:42.113 INFO:tasks.workunit.client.salt_master.target158069067036.stdout:Repository 'update' is up to date.
2018-10-26T19:49:42.254 INFO:tasks.workunit.client.salt_master.target158069067036.stdout:All repositories have been refreshed.
```

There is a significant difference between the `deepsea` repo and the other repos - only the `deepsea` repo is produced by Jenkins, and is unsigned, while the other repos are produced by IBS. When I add the repo on my laptop and try to refresh it, I get:

```
wilbur:/home/smithfarm # zypper addrepo http://ceph-ci.suse.de/artifacts/jenkins/deepsea-pr/suse:tier1/280/ deepsea
Adding repository 'deepsea' ........................................................................................[done]
Repository 'deepsea' successfully added

URI         : http://ceph-ci.suse.de/artifacts/jenkins/deepsea-pr/suse:tier1/280/
Enabled     : Yes
GPG Check   : Yes
Autorefresh : No
Priority    : 99 (default priority)

Repository priorities are without effect. All enabled repositories share the same priority.
wilbur:/home/smithfarm # zypper ref deepsea
Retrieving repository 'deepsea' metadata ------------------------------------------------------------------------------[\]
Warning: File 'repomd.xml' from repository 'deepsea' is unsigned.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: We can't verify that no one meddled with this file, so it might not be trustworthy
    anymore! You should not continue unless you know it's safe.

File 'repomd.xml' from repository 'deepsea' is unsigned, continue? [yes/no] (no): yes
Retrieving repository 'deepsea' metadata ...........................................................................[done]
Building repository 'deepsea' cache ................................................................................[done]
Specified repositories have been refreshed.
```

I cannot reproduce the `[deepsea|http://ceph-ci.suse.de/artifacts/jenkins/deepsea-pr/suse:tier1/280] Valid metadata not found at specified URL` error, though.

### Steps to Reproduce Issue

`@susebot run teuthology` in a PR targeting master.

**Comment by smithfarm** [comment]
@jschmid1 @kshtsk This is the CI issue currently presenting in #1435

**Comment by kshtsk** [comment]
@smithfarm This issue is not related to #1435 and reproduced on master branch, which can mean that PR introducer has been merged without passing tier1 earlier.

**Comment by kshtsk** [comment]
Does deepsea/salt adds the packages on it's own to some node?

**Comment by kshtsk** [comment]
The issue started to be reproduced after commit:
https://github.com/SUSE/DeepSea/pull/1431/commits/6ddd5aba12737c4a64b242f9b50aba04badbf84d
which added 7 days ago and merged within PR https://github.com/SUSE/DeepSea/pull/1431 without passing the suse:tier1 (because latest passed https://github.com/SUSE/DeepSea/pull/1431#issuecomment-430934864 check was 9 days ago, i.e. before adding the commit to the PR #1431).

**Comment by smithfarm** [comment]
@kshtsk Thanks for the root cause analysis. I think the fix is to add package-signing to the deepsea-rpm-builder.

**Comment by kshtsk** [comment]
> Which OS were you attempting to reproduce this on, by the way? Tumbleweed? I tried it on Leap 15.0. The actual error in the tests is happening in SLE-15-SP0. Each one might have different behavior.

Initially I've been checking for Tumbleweed, but later I've checked on both Leap 42.3 and 15.0, everywhere is the same result.
> 
> For example, in Leap 15.0 the `zypper ref -f deepsea` succeeds even when the repo's "GPG Check" bit is set:

The key word **non-interactive**, your mistake is running zypper in interactive mode, try and run zypper as I pointed in my examples, with `-n` option.  

Interesting, from my memory the deepsea repo is adding to nodes with `--gpg-nocheck`, does it mean salt modifies the repos enabling gpg-check or it adds repos itself?

**Comment by smithfarm** [comment]
I think I know what is causing this, or at least I think I know how to stop it from happening. More in a bit.

**Comment by smithfarm** [comment]
@kshtsk DeepSea itself should not be adding any repos to any nodes. This (adding of repos) is done by the teuthology install task, and the repos are definitely being added with `gpgcheck=0` which should unconditionally disable all GPG checks for that repo.

**Comment by kshtsk** [comment]
> @kshtsk DeepSea itself should not be adding any repos to any nodes. This (adding of repos) is done by the teuthology install task (for all test nodes the same), and the repos are definitely being added with `gpgcheck=0` which should unconditionally disable all GPG checks for all repos.

Yes, I know, but who is changing the GPG check flag in this particular case.

**Comment by smithfarm** [comment]
@kshtsk Very strange. I cannot reproduce the failure in BHS1.

**Comment by smithfarm** [comment]
@kshtsk Exactly. That's why I wrote "very strange".

**Comment by kshtsk** [comment]
So... the issue is reproduced when deploying teuthology with custom nameserver, requires more investigation why it is happening. Probably stage 4 or earlier is doing something strange with DNS or network system before an attempt to refresh in `setup prometheus rgw exporter`.

**Comment by smithfarm** [comment]
The big question is: how does the custom nameserver resolve the testnode's hostnames - e.g. `target158069066101.teuthology` ?

**Comment by kshtsk** [comment]
> The big question is: how does the custom nameserver resolve the testnode's hostnames - e.g. `target158069066101.teuthology` ?
> 
> The dnsmasq nameserver running on the teuthology VM will resolve this hostname to 158.69.66.101

Because custom nameserver is configured the same way as teuthology dnsmasq.
Try yourself:
```
$ nslookup target158069066101.teuthology ceph-ci.suse.de
Server:		ceph-ci.suse.de
Address:	158.69.90.90#53

Name:	target158069066101.teuthology
Address: 158.69.66.101
```

**Comment by kshtsk** [comment]
@smithfarm Of course there is 158.69.90.90 IP address used for setting targets up.

**Comment by smithfarm** [comment]
Thanks, @kshtsk
