### ISSUE TITLE
Stage 0 fails cause of `ceph.updates.default.zypper update` failed.

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/DeepSea#15]
Hi Eric,

While running stage 0, I got this stack trace:

```
The minion function caused an exception: Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1320, in _thread_return
    return_data = executor.execute()
File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
    return self.func(*self.args, **self.kwargs)
File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 942, in sls
    ret = st_.state.call_high(high_)
File "/usr/lib/python2.7/site-packages/salt/state.py", line 2276, in call_high
    ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
File "/usr/lib/python2.7/site-packages/salt/state.py", line 1799, in call_chunks
    running = self.call_chunk(low, running, chunks)
File "/usr/lib/python2.7/site-packages/salt/state.py", line 2163, in call_chunk
    self.event(running[tag], len(chunks), fire_event=low.get('fire_event'))
File "/usr/lib/python2.7/site-packages/salt/state.py", line 1955, in event
    [self.jid, self.opts['id'], str(chunk_ret['name'])], 'state_result'
KeyError: 'name'
```

To find the cause, I've modified `/usr/lib/python2.7/site-packages/salt/state.py` to print `chunk_ret`:

```
{
    'comment': 'One or more requisite failed: ceph.updates.default.zypper update',
    '__run_num__': 1, 
    '__sls__': u'ceph.updates.default', 
    'changes': {}, 
    'result': False
}
```

Then, I enabled the debug log on the admin minion, which revealed that `zypper --non-interactive update --replacefiles` failed:

```
admin:/srv # zypper --non-interactive update --replacefiles
Loading repository data...
Reading installed packages...

The following 9 package updates will NOT be installed:
  augeas-lenses ... snip ... p11-kit p11-kit-tools ruby2.1-rubygem-facter rubygem-facter

The following 9 NEW packages are going to be installed:
  ruby2.1-rubygem-bundler ruby2.1-rubygem-chef-zero-4_9 ... snip ...

The following 199 packages are going to be upgraded:
  aaa_base aaa_base-extras .. snip ... rubygem-facter ... snip ...  zypper-log

199 packages to upgrade, 9 new.
Overall download size: 13.5 MiB. Already cached: 188.4 MiB. After the operation, additional 29.9 MiB will be used.
Continue? [y/n/? shows all options] (y): y
In cache desktop-translations-20151007-4.1.noarch.rpm                                             (1/208),   5.1 MiB ( 41.6 MiB unpacked)
... snip ...                                                   (154/208), 109.4 KiB (179.9 KiB unpacked)
In cache rubygem-hiera-1.3.4-17.2.x86_64.rpm                                                    (155/208),   5.7 KiB (  426   B unpacked)
Retrieving package rubygem-facter-2.4.6-1.2.x86_64                                              (156/208),  11.2 KiB (  952   B unpacked)
Retrieving: rubygem-facter-2.4.6-1.2.x86_64.rpm .....................................................[error]
File './x86_64/rubygem-facter-2.4.6-1.2.x86_64.rpm' not found on medium 'http://download.opensuse.org/repositories/systemsmanagement:/puppet/openSUSE_Leap_42.1/'

Abort, retry, ignore? [a/r/i/? shows all options] (a): a
Problem occured during or after installation or removal of packages:
Installation aborted by user                                                                                                             

Please see the above error message for a hint.
```

Running a `zypper refresh` fixed this issue.

**See also: https://github.com/saltstack/salt/issues/36687**

**Comment by jan--f** [comment]
Closing cause seems outdated. @sebastian-philipp please repoen if issue still persists.
