### ISSUE TITLE
openstack.integrate fails

### ISSUE THREAD

**Issue by hemna** [SUSE/DeepSea#1513]
### Description of Issue/Question
```
ses-admin:/srv/modules/runners # salt-run --out=yaml openstack.integrate
# [WARNING ] /srv/modules/runners/filequeue.py:337: DeprecationWarning: Use of 'salt.utils.alias_function' detected. This function has been moved to 'salt.utils.functools.alias_function' as of Salt 2018.3.0. This warning will be removed in Salt Neon.

# [WARNING ] /usr/lib/python2.7/site-packages/salt/client/__init__.py:719: DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.

ERROR:
- - "Rendering SLS 'base:ceph.openstack.glance.key.default' failed: Jinja error: coercing
    to Unicode: need string or buffer, NoneType found\nTraceback (most recent call
    last):\n  File \"/usr/lib/python2.7/site-packages/salt/utils/templates.py\", line
    381, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File
    \"/usr/lib/python2.7/site-packages/jinja2/environment.py\", line 989, in render\n
    \   return self.environment.handle_exception(exc_info, True)\n  File \"/usr/lib/python2.7/site-packages/jinja2/environment.py\",
    line 754, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File \"<template>\",
    line 13, in top-level template code\n  File \"/var/cache/salt/minion/extmods/modules/keyring.py\",
    line 16, in secret\n    if os.path.exists(filename):\n  File \"/usr/lib64/python2.7/genericpath.py\",
    line 26, in exists\n    os.stat(path)\nTypeError: coercing to Unicode: need string
    or buffer, NoneType found\n\n; line 13\n\n---\n[...]\n    - group: salt\n    -
    mode: 600\n    - makedirs: True\n    - context:\n      client: client.{{ prefix
    }}glance\n      secret: {{ salt['keyring.secret'](keyring_file) }}    <======================\n
    \     prefix: \"{{ prefix }}\"\n    - fire_event: True\n\n\nTraceback (most recent
    call last):\n[...]\n---"
  - "Detected conflicting IDs, SLS IDs need to be globally unique.\n    The conflicting
    ID is 'auth None' and is found in SLS 'base:ceph.openstack.glance.auth.default'
    and SLS 'base:ceph.openstack.cinder.auth.default'"
  - "Rendering SLS 'base:ceph.openstack.cinder.key.default' failed: Jinja error: coercing
    to Unicode: need string or buffer, NoneType found\nTraceback (most recent call
    last):\n  File \"/usr/lib/python2.7/site-packages/salt/utils/templates.py\", line
    381, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File
    \"/usr/lib/python2.7/site-packages/jinja2/environment.py\", line 989, in render\n
    \   return self.environment.handle_exception(exc_info, True)\n  File \"/usr/lib/python2.7/site-packages/jinja2/environment.py\",
    line 754, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File \"<template>\",
    line 13, in top-level template code\n  File \"/var/cache/salt/minion/extmods/modules/keyring.py\",
    line 16, in secret\n    if os.path.exists(filename):\n  File \"/usr/lib64/python2.7/genericpath.py\",
    line 26, in exists\n    os.stat(path)\nTypeError: coercing to Unicode: need string
    or buffer, NoneType found\n\n; line 13\n\n---\n[...]\n    - group: salt\n    -
    mode: 600\n    - makedirs: True\n    - context:\n      client: client.{{ prefix
    }}cinder\n      secret: {{ salt['keyring.secret'](keyring_file) }}    <======================\n
    \     prefix: \"{{ prefix }}\"\n    - fire_event: True\n\n\nTraceback (most recent
    call last):\n[...]\n---"
  - "Detected conflicting IDs, SLS IDs need to be globally unique.\n    The conflicting
    ID is 'auth None' and is found in SLS 'base:ceph.openstack.cinder.auth.default'
    and SLS 'base:ceph.openstack.cinder-backup.auth.default'"
  - "Rendering SLS 'base:ceph.openstack.cinder-backup.key.default' failed: Jinja error:
    coercing to Unicode: need string or buffer, NoneType found\nTraceback (most recent
    call last):\n  File \"/usr/lib/python2.7/site-packages/salt/utils/templates.py\",
    line 381, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n
    \ File \"/usr/lib/python2.7/site-packages/jinja2/environment.py\", line 989, in
    render\n    return self.environment.handle_exception(exc_info, True)\n  File \"/usr/lib/python2.7/site-packages/jinja2/environment.py\",
    line 754, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File \"<template>\",
    line 13, in top-level template code\n  File \"/var/cache/salt/minion/extmods/modules/keyring.py\",
    line 16, in secret\n    if os.path.exists(filename):\n  File \"/usr/lib64/python2.7/genericpath.py\",
    line 26, in exists\n    os.stat(path)\nTypeError: coercing to Unicode: need string
    or buffer, NoneType found\n\n; line 13\n\n---\n[...]\n    - group: salt\n    -
    mode: 600\n    - makedirs: True\n    - context:\n      client: client.{{ prefix
    }}cinder-backup\n      secret: {{ salt['keyring.secret'](keyring_file) }}    <======================\n
    \     prefix: \"{{ prefix }}\"\n    - fire_event: True\n\n\nTraceback (most recent
    call last):\n[...]\n---"
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt-run --out=yaml openstack.integrate

### Versions Report

```
ses-admin:/srv/modules/runners # salt-run deepsea.version
[WARNING ] /srv/modules/runners/filequeue.py:337: DeprecationWarning: Use of 'salt.utils.alias_function' detected. This function has been moved to 'salt.utils.functools.alias_function' as of Salt 2018.3.0. This warning will be removed in Salt Neon.

0.8.8+git.0.d6faf0eac

ses-admin:/srv/modules/runners # rpm -qi salt-minion
Name        : salt-minion
Version     : 2018.3.0
Release     : 46.47.2
Architecture: x86_64
Install Date: Fri Jan 18 13:42:31 2019
Group       : System/Management
Size        : 39745
License     : Apache-2.0
Signature   : RSA/SHA256, Fri Nov 23 16:49:03 2018, Key ID 70af9e8139db7c82
Source RPM  : salt-2018.3.0-46.47.2.src.rpm
Build Date  : Fri Nov 23 16:45:00 2018
Build Host  : sheep24
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : SUSE LLC <https://www.suse.com/>
URL         : http://saltstack.org/
Summary     : The client component for Saltstack
Description :
Salt minion is queried and controlled from the master.
Listens to the salt master and execute the commands.
Distribution: SUSE Linux Enterprise 12

ses-admin:/srv/modules/runners # rpm -qi salt-master
Name        : salt-master
Version     : 2018.3.0
Release     : 46.47.2
Architecture: x86_64
Install Date: Fri Jan 18 13:42:28 2019
Group       : System/Management
Size        : 2331410
License     : Apache-2.0
Signature   : RSA/SHA256, Fri Nov 23 16:49:03 2018, Key ID 70af9e8139db7c82
Source RPM  : salt-2018.3.0-46.47.2.src.rpm
Build Date  : Fri Nov 23 16:45:00 2018
Build Host  : sheep24
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : SUSE LLC <https://www.suse.com/>
URL         : http://saltstack.org/
Summary     : The management component of Saltstack with zmq protocol supported
Description :
The Salt master is the central server to which all minions connect.
Enabled commands to remote systems to be called in parallel rather
than serially.
Distribution: SUSE Linux Enterprise 12
```

**Comment by hemna** [comment]
```
ses-admin:~ # salt-run openstack.integrate
[WARNING ] /srv/modules/runners/filequeue.py:337: DeprecationWarning: Use of 'salt.utils.alias_function' detected. This function has been moved to 'salt.utils.functools.alias_function' as of Salt 2018.3.0. This warning will be removed in Salt Neon.

[WARNING ] /usr/lib/python2.7/site-packages/salt/client/__init__.py:719: DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.

ERROR:
    |_
      - Rendering SLS 'base:ceph.openstack.glance.key.default' failed: Jinja error: coercing to Unicode: need string or buffer, NoneType found
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 381, in render_jinja_tmpl
            output = template.render(**decoded_context)
          File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
            return self.environment.handle_exception(exc_info, True)
          File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
            reraise(exc_type, exc_value, tb)
          File "<template>", line 13, in top-level template code
          File "/var/cache/salt/minion/extmods/modules/keyring.py", line 16, in secret
            if os.path.exists(filename):
          File "/usr/lib64/python2.7/genericpath.py", line 26, in exists
            os.stat(path)
        TypeError: coercing to Unicode: need string or buffer, NoneType found
        
        ; line 13
        
        ---
        [...]
            - group: salt
            - mode: 600
            - makedirs: True
            - context:
              client: client.{{ prefix }}glance
              secret: {{ salt['keyring.secret'](keyring_file) }}    <======================
              prefix: "{{ prefix }}"
            - fire_event: True
        
        
        Traceback (most recent call last):
        [...]
        ---
      - Detected conflicting IDs, SLS IDs need to be globally unique.
            The conflicting ID is 'auth None' and is found in SLS 'base:ceph.openstack.glance.auth.default' and SLS 'base:ceph.openstack.cinder.auth.default'
      - Rendering SLS 'base:ceph.openstack.cinder.key.default' failed: Jinja error: coercing to Unicode: need string or buffer, NoneType found
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 381, in render_jinja_tmpl
            output = template.render(**decoded_context)
          File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
            return self.environment.handle_exception(exc_info, True)
          File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
            reraise(exc_type, exc_value, tb)
          File "<template>", line 13, in top-level template code
          File "/var/cache/salt/minion/extmods/modules/keyring.py", line 16, in secret
            if os.path.exists(filename):
          File "/usr/lib64/python2.7/genericpath.py", line 26, in exists
            os.stat(path)
        TypeError: coercing to Unicode: need string or buffer, NoneType found
        
        ; line 13
        
        ---
        [...]
            - group: salt
            - mode: 600
            - makedirs: True
            - context:
              client: client.{{ prefix }}cinder
              secret: {{ salt['keyring.secret'](keyring_file) }}    <======================
              prefix: "{{ prefix }}"
            - fire_event: True
        
        
        Traceback (most recent call last):
        [...]
        ---
      - Detected conflicting IDs, SLS IDs need to be globally unique.
            The conflicting ID is 'auth None' and is found in SLS 'base:ceph.openstack.cinder.auth.default' and SLS 'base:ceph.openstack.cinder-backup.auth.default'
      - Rendering SLS 'base:ceph.openstack.cinder-backup.key.default' failed: Jinja error: coercing to Unicode: need string or buffer, NoneType found
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 381, in render_jinja_tmpl
            output = template.render(**decoded_context)
          File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
            return self.environment.handle_exception(exc_info, True)
          File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
            reraise(exc_type, exc_value, tb)
          File "<template>", line 13, in top-level template code
          File "/var/cache/salt/minion/extmods/modules/keyring.py", line 16, in secret
            if os.path.exists(filename):
          File "/usr/lib64/python2.7/genericpath.py", line 26, in exists
            os.stat(path)
        TypeError: coercing to Unicode: need string or buffer, NoneType found
        
        ; line 13
        
        ---
        [...]
            - group: salt
            - mode: 600
            - makedirs: True
            - context:
              client: client.{{ prefix }}cinder-backup
              secret: {{ salt['keyring.secret'](keyring_file) }}    <======================
              prefix: "{{ prefix }}"
            - fire_event: True
        
        
        Traceback (most recent call last):
        [...]
        ---

```

**Comment by hemna** [comment]
reinstall seems to have fixed this.
