### ISSUE TITLE
Stage 3 fails transiently in OVH

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#432]
As of Milestone 8 we are seeing intermittent failures due to timeouts. They don't seem to be limited to any particular test job/configuration, but one of the failure modalities is that Stage 3 fails with the following output:

```
2017-07-10T11:52:37.536 INFO:teuthology.orchestra.run.target149202179181.stderr:+ echo '*********************************************'
2017-07-10T11:52:37.536 INFO:teuthology.orchestra.run.target149202179181.stderr:+ echo '********** Running DeepSea Stage 3 **********'
2017-07-10T11:52:37.536 INFO:teuthology.orchestra.run.target149202179181.stderr:+ echo '*********************************************'
2017-07-10T11:52:37.537 INFO:teuthology.orchestra.run.target149202179181.stderr:+ echo ''
2017-07-10T11:52:37.537 INFO:teuthology.orchestra.run.target149202179181.stderr:+ tee /tmp/stage.3.log
2017-07-10T11:52:37.537 INFO:teuthology.orchestra.run.target149202179181.stderr:+ salt-run --no-color state.orch ceph.stage.3
2017-07-10T11:52:38.093 INFO:teuthology.orchestra.run.target149202179181.stderr:[WARNING ] Unable to find IPv6 record for "target149202179181.teuthology" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
2017-07-10T11:52:38.508 INFO:teuthology.orchestra.run.target149202179181.stderr:[WARNING ] Unable to find IPv6 record for "target149202179181.teuthology" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
2017-07-10T11:52:38.948 INFO:teuthology.orchestra.run.target149202179181.stderr:[WARNING ] Unable to find IPv6 record for "target149202179181.teuthology" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
2017-07-10T11:52:39.895 INFO:teuthology.orchestra.run.target149202179181.stderr:[WARNING ] Unable to find IPv6 record for "target149202179181.teuthology" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
2017-07-10T11:58:24.106 INFO:teuthology.orchestra.run.target149202179181.stderr:[ERROR   ] Run failed on minions: target149202179181.teuthology
2017-07-10T11:58:24.107 INFO:teuthology.orchestra.run.target149202179181.stderr:Failures:
2017-07-10T11:58:24.107 INFO:teuthology.orchestra.run.target149202179181.stderr:    target149202179181.teuthology:
2017-07-10T11:58:24.108 INFO:teuthology.orchestra.run.target149202179181.stderr:    ----------
2017-07-10T11:58:24.108 INFO:teuthology.orchestra.run.target149202179181.stderr:              ID: wait
2017-07-10T11:58:24.108 INFO:teuthology.orchestra.run.target149202179181.stderr:        Function: module.run
2017-07-10T11:58:24.108 INFO:teuthology.orchestra.run.target149202179181.stderr:            Name: wait.out
2017-07-10T11:58:24.108 INFO:teuthology.orchestra.run.target149202179181.stderr:          Result: False
2017-07-10T11:58:24.108 INFO:teuthology.orchestra.run.target149202179181.stderr:         Comment: Module function wait.out threw an exception. Exception: Timeout expired
2017-07-10T11:58:24.108 INFO:teuthology.orchestra.run.target149202179181.stderr:         Started: 11:53:23.529829
2017-07-10T11:58:24.109 INFO:teuthology.orchestra.run.target149202179181.stderr:        Duration: 300502.688 ms
2017-07-10T11:58:24.109 INFO:teuthology.orchestra.run.target149202179181.stderr:         Changes:
2017-07-10T11:58:24.109 INFO:teuthology.orchestra.run.target149202179181.stderr:
2017-07-10T11:58:24.109 INFO:teuthology.orchestra.run.target149202179181.stderr:    Summary for target149202179181.teuthology
2017-07-10T11:58:24.109 INFO:teuthology.orchestra.run.target149202179181.stderr:    ------------
2017-07-10T11:58:24.109 INFO:teuthology.orchestra.run.target149202179181.stderr:    Succeeded: 0
2017-07-10T11:58:24.109 INFO:teuthology.orchestra.run.target149202179181.stderr:    Failed:    1
2017-07-10T11:58:24.110 INFO:teuthology.orchestra.run.target149202179181.stderr:    ------------
2017-07-10T11:58:24.110 INFO:teuthology.orchestra.run.target149202179181.stderr:    Total states run:     1
2017-07-10T11:58:24.110 INFO:teuthology.orchestra.run.target149202179181.stderr:    Total run time: 300.503 s
2017-07-10T11:58:24.110 INFO:teuthology.orchestra.run.target149202179181.stderr:
2017-07-10T11:58:24.171 INFO:teuthology.orchestra.run.target149202179181.stdout:firewall                 : [1m[92mdisabled[0m
2017-07-10T11:58:24.171 INFO:teuthology.orchestra.run.target149202179181.stdout:apparmor                 : [1m[92mdisabled[0m
2017-07-10T11:58:24.171 INFO:teuthology.orchestra.run.target149202179181.stdout:DEV_ENV                  : [1m[92mTrue[0m
2017-07-10T11:58:24.171 INFO:teuthology.orchestra.run.target149202179181.stdout:fsid                     : [1m[92mvalid[0m
2017-07-10T11:58:24.171 INFO:teuthology.orchestra.run.target149202179181.stdout:public_network           : [1m[92mvalid[0m
2017-07-10T11:58:24.171 INFO:teuthology.orchestra.run.target149202179181.stdout:cluster_network          : [1m[92mvalid[0m
2017-07-10T11:58:24.171 INFO:teuthology.orchestra.run.target149202179181.stdout:cluster_interface        : [1m[92mvalid[0m
2017-07-10T11:58:24.172 INFO:teuthology.orchestra.run.target149202179181.stdout:monitors                 : [1m[92mvalid[0m
2017-07-10T11:58:24.172 INFO:teuthology.orchestra.run.target149202179181.stdout:mgrs                     : [1m[92mvalid[0m
2017-07-10T11:58:24.172 INFO:teuthology.orchestra.run.target149202179181.stdout:storage                  : [1m[92mvalid[0m
2017-07-10T11:58:24.172 INFO:teuthology.orchestra.run.target149202179181.stdout:ganesha                  : [1m[92mvalid[0m
2017-07-10T11:58:24.172 INFO:teuthology.orchestra.run.target149202179181.stdout:master_role              : [1m[92mvalid[0m
2017-07-10T11:58:24.172 INFO:teuthology.orchestra.run.target149202179181.stdout:mon_host                 : [1m[92mvalid[0m
2017-07-10T11:58:24.172 INFO:teuthology.orchestra.run.target149202179181.stdout:mon_initial_members      : [1m[92mvalid[0m
2017-07-10T11:58:24.172 INFO:teuthology.orchestra.run.target149202179181.stdout:time_server              : [1m[92mvalid[0m
2017-07-10T11:58:24.173 INFO:teuthology.orchestra.run.target149202179181.stdout:fqdn                     : [1m[92mvalid[0m
2017-07-10T11:58:24.173 INFO:teuthology.orchestra.run.target149202179181.stdout:target149202179181.teuthology_master:
2017-07-10T11:58:24.173 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: time - Function: salt.state - Result: Changed Started: - 11:52:40.691160 Duration: 2624.724 ms
2017-07-10T11:58:24.173 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: packages - Function: salt.state - Result: Clean Started: - 11:52:43.316174 Duration: 10360.789 ms
2017-07-10T11:58:24.173 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: configuration check - Function: salt.state - Result: Clean Started: - 11:52:53.677555 Duration: 479.049 ms
2017-07-10T11:58:24.173 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: configuration - Function: salt.state - Result: Changed Started: - 11:52:54.156784 Duration: 799.85 ms
2017-07-10T11:58:24.173 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: admin - Function: salt.state - Result: Changed Started: - 11:52:54.957033 Duration: 602.908 ms
2017-07-10T11:58:24.173 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: mgr keyrings - Function: salt.state - Result: Changed Started: - 11:52:55.560110 Duration: 518.305 ms
2017-07-10T11:58:24.174 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: monitors - Function: salt.state - Result: Changed Started: - 11:52:56.078719 Duration: 839.121 ms
2017-07-10T11:58:24.174 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: mgr auth - Function: salt.state - Result: Changed Started: - 11:52:56.918079 Duration: 1619.991 ms
2017-07-10T11:58:24.174 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: mgrs - Function: salt.state - Result: Changed Started: - 11:52:58.538326 Duration: 1443.52 ms
2017-07-10T11:58:24.174 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: setup ceph exporter - Function: salt.state - Result: Changed Started: - 11:52:59.982276 Duration: 11465.179 ms
2017-07-10T11:58:24.174 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: osd auth - Function: salt.state - Result: Changed Started: - 11:53:11.448071 Duration: 1369.322 ms
2017-07-10T11:58:24.174 INFO:teuthology.orchestra.run.target149202179181.stdout:  Name: storage - Function: salt.state - Result: Changed Started: - 11:53:12.817578 Duration: 10335.073 ms
2017-07-10T11:58:24.174 INFO:teuthology.orchestra.run.target149202179181.stdout:----------
2017-07-10T11:58:24.174 INFO:teuthology.orchestra.run.target149202179181.stdout:          ID: pools
2017-07-10T11:58:24.175 INFO:teuthology.orchestra.run.target149202179181.stdout:    Function: salt.state
2017-07-10T11:58:24.175 INFO:teuthology.orchestra.run.target149202179181.stdout:      Result: False
2017-07-10T11:58:24.175 INFO:teuthology.orchestra.run.target149202179181.stdout:     Comment: Run failed on minions: target149202179181.teuthology
2017-07-10T11:58:24.175 INFO:teuthology.orchestra.run.target149202179181.stdout:              Failures:
2017-07-10T11:58:24.175 INFO:teuthology.orchestra.run.target149202179181.stdout:                  target149202179181.teuthology:
2017-07-10T11:58:24.175 INFO:teuthology.orchestra.run.target149202179181.stdout:                  ----------
2017-07-10T11:58:24.175 INFO:teuthology.orchestra.run.target149202179181.stdout:                            ID: wait
2017-07-10T11:58:24.175 INFO:teuthology.orchestra.run.target149202179181.stdout:                      Function: module.run
2017-07-10T11:58:24.175 INFO:teuthology.orchestra.run.target149202179181.stdout:                          Name: wait.out
2017-07-10T11:58:24.176 INFO:teuthology.orchestra.run.target149202179181.stdout:                        Result: False
2017-07-10T11:58:24.176 INFO:teuthology.orchestra.run.target149202179181.stdout:                       Comment: Module function wait.out threw an exception. Exception: Timeout expired
2017-07-10T11:58:24.176 INFO:teuthology.orchestra.run.target149202179181.stdout:                       Started: 11:53:23.529829
2017-07-10T11:58:24.176 INFO:teuthology.orchestra.run.target149202179181.stdout:                      Duration: 300502.688 ms
2017-07-10T11:58:24.176 INFO:teuthology.orchestra.run.target149202179181.stdout:                       Changes:
2017-07-10T11:58:24.176 INFO:teuthology.orchestra.run.target149202179181.stdout:
2017-07-10T11:58:24.176 INFO:teuthology.orchestra.run.target149202179181.stdout:                  Summary for target149202179181.teuthology
2017-07-10T11:58:24.176 INFO:teuthology.orchestra.run.target149202179181.stdout:                  ------------
2017-07-10T11:58:24.176 INFO:teuthology.orchestra.run.target149202179181.stdout:                  Succeeded: 0
2017-07-10T11:58:24.177 INFO:teuthology.orchestra.run.target149202179181.stdout:                  Failed:    1
2017-07-10T11:58:24.177 INFO:teuthology.orchestra.run.target149202179181.stdout:                  ------------
2017-07-10T11:58:24.177 INFO:teuthology.orchestra.run.target149202179181.stdout:                  Total states run:     1
2017-07-10T11:58:24.177 INFO:teuthology.orchestra.run.target149202179181.stdout:                  Total run time: 300.503 s
2017-07-10T11:58:24.177 INFO:teuthology.orchestra.run.target149202179181.stdout:     Started: 11:53:23.153234
2017-07-10T11:58:24.177 INFO:teuthology.orchestra.run.target149202179181.stdout:    Duration: 300953.46 ms
2017-07-10T11:58:24.177 INFO:teuthology.orchestra.run.target149202179181.stdout:     Changes:
2017-07-10T11:58:24.177 INFO:teuthology.orchestra.run.target149202179181.stdout:
2017-07-10T11:58:24.177 INFO:teuthology.orchestra.run.target149202179181.stdout:Summary for target149202179181.teuthology_master
2017-07-10T11:58:24.178 INFO:teuthology.orchestra.run.target149202179181.stdout:-------------
2017-07-10T11:58:24.178 INFO:teuthology.orchestra.run.target149202179181.stdout:Succeeded: 12 (changed=10)
2017-07-10T11:58:24.178 INFO:teuthology.orchestra.run.target149202179181.stdout:Failed:     1
2017-07-10T11:58:24.178 INFO:teuthology.orchestra.run.target149202179181.stdout:-------------
2017-07-10T11:58:24.178 INFO:teuthology.orchestra.run.target149202179181.stdout:Total states run:     13
2017-07-10T11:58:24.178 INFO:teuthology.orchestra.run.target149202179181.stdout:Total run time:  343.411 s
```

Teuthology link: http://149.202.178.223:8081/ubuntu-2017-07-10_11:41:12-deepsea:basic-ses5---basic-openstack/105/

**Comment by smithfarm** [comment]
Logs can be obtained by running: `wget -r --no-parent -nH --cut-dirs=2 http://149.202.178.223/ubuntu-2017-07-10_11:41:12-deepsea:basic-ses5---basic-openstack/105/remote/`

**Comment by smithfarm** [comment]
Note: these timeouts were never observed prior to Milestone 8

**Comment by smithfarm** [comment]
Reproduced the issue two more times:

* http://147.135.133.225:8081/ubuntu-2017-07-11_11:18:24-deepsea-ses5---basic-openstack/5/
* http://147.135.133.225:8081/ubuntu-2017-07-11_11:18:24-deepsea-ses5---basic-openstack/9/

**Comment by smithfarm** [comment]
So far i've determined that:

* the error occurs in the communication between the two Salt daemons (master and minion) running on the Salt master node
* systemd reports a permissions problem on `/var/run/salt-master.pid` on that machine
* a strange error message `[salt.transport.ipc][ERROR   ][6171] Exception occurred while handling stream: [Errno 0] Success` is logged during stage 3, at about the same time as the failure happens

From `/var/log/salt/master`

```
2017-07-10 11:49:52,849 [salt.utils.parsers][WARNING ][4997] Master received a SIGTERM. Exiting.
2017-07-10 11:49:52,851 [salt.utils.parsers][ERROR   ][4997] [Errno 13] Permission denied: '/var/run/salt-master.pid'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 252, in exit
    mixin_before_exit_func(self)
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 884, in _mixin_before_exit
    os.unlink(self.config['pidfile'])
OSError: [Errno 13] Permission denied: '/var/run/salt-master.pid'
2017-07-10 11:49:52,854 [salt.utils.parsers][ERROR   ][4997] Error while processing <unbound method DaemonMixIn._mixin_before_exit>: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 252, in exit
    mixin_before_exit_func(self)
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 884, in _mixin_before_exit
    os.unlink(self.config['pidfile'])
OSError: [Errno 13] Permission denied: '/var/run/salt-master.pid'
```

That happens when the deepsea task restarts the salt-master.service; i.e. long before stage 3 starts. So possibly unrelated and harmless.

Then there's this beauty:

```
2017-07-10 11:52:40,663 [salt.transport.ipc][ERROR   ][6171] Exception occurred while handling stream: [Errno 0] Success
```

And, finally:

```
2017-07-10 11:58:24,106 [salt.state       ][ERROR   ][10436] Run failed on minions: target149202179181.teuthology
Failures:
    target149202179181.teuthology:
    ----------
              ID: wait
        Function: module.run
            Name: wait.out
          Result: False
         Comment: Module function wait.out threw an exception. Exception: Timeout expired
         Started: 11:53:23.529829
        Duration: 300502.688 ms
         Changes:   
    
    Summary for target149202179181.teuthology
    ------------
    Succeeded: 0
    Failed:    1
    ------------
    Total states run:     1
    Total run time: 300.503 s
```

The minion log has only this to offer:

```
2017-07-10 11:58:24,030 [salt.state       ][ERROR   ][11902] Module function wait.out threw an exception. Exception: Timeout expired
```

**Comment by smithfarm** [comment]
Possibly related:

* https://github.com/saltstack/salt/issues/34460
* https://github.com/saltstack/salt/pull/41409
* https://github.com/openSUSE/salt/pull/32
* https://bugzilla.suse.com/show_bug.cgi?id=1042854

**Comment by smithfarm** [comment]
Salt version

```
target149202176208:/home/ubuntu # rpm -q salt-master
salt-master-2016.11.4-45.2.x86_64
```

**Comment by smithfarm** [comment]
It looks like we're running this version [1] which apparently does not yet include the fix - i.e. changes file does not mention it.

[1] https://build.suse.de/request/show/133921

**Comment by smithfarm** [comment]
@swiftgist Any idea what's going on here? I don't know for sure, but I have a feeling that the earlier runs (which did not exhibit this behavior) might have been on whatever salt was in SP3 before the last update to 2016.11.4.

**Comment by smithfarm** [comment]
Hm, now that I think about it, the minions running in the tests have two masters: the master instance on the teuthology VM, and the master instance in the test. The first master is used to provision the test nodes, before the test starts. It needs to clean up its minion keys just before it exits.

**Comment by swiftgist** [comment]
I believe we have been on salt 2016.11.4 for a while.  The previous version I have to salt-2016.11.4-45.2.x86_64 is salt-2016.11.4-4.3.x86_64.  

I have yet to track down the "permission denied" issue with the salt-master complaining about access to files owned by salt:salt.  Trying to reproduce the error immediately has not worked.  That problem seems to be temporary in my experience.  (That doesn't make it any better.)

The timeout exception is the failsafe we put in there when something really went wrong.  Waiting 5 minutes is likely overkill for most operations.  We could add others to something more reasonable, but the issue is the Ceph cluster is in HEALTH_ERR for some reason that did not seem temporary.

Currently, the call in /srv/salt/ceph/pool/default.sls waits until the cluster is not in a HEALTH_ERR state.  The original intention is to let Ceph settle before proceeding to Stage 4.  (Although everyone is running Stage 3 and 4 manually, this is not required.)  We could improve the message to something like "Timeout expired after {} seconds in HEALTH_ERR".  I don't know if that would be considered any better.

**Comment by smithfarm** [comment]
I suspect the HEALTH_ERR is caused by a Salt malfunction in this case, but I'm missing an indication of what part of Stage 3 failed. I see:

```
Summary for target149202179181.teuthology_master
-------------
Succeeded: 12 (changed=10)
Failed:     1
-------------
```

What does the 12, 10, and 1 signify? I assume some kind of steps that Stage 3 consists of, but what are they, and which one failed? I realize this is probably just me being dense, but I couldn't find it in any of the logs.

**Comment by swiftgist** [comment]
Stage 3 has 15 states, but two are conditional  and normally excluded.  So, 12 states succeeded and 1 failed.  The changed=10 is letting you know how many actually ran vs. Salt deciding that the state didn't need to run.

An example of not needing to run a state is when configuration file is already correct.  Salt will list that state as clean.  BTW, DeepSea sets the `state_output: mixed`.  Otherwise, even the successes are many lines of text.  

The failed there would match the timeout expiring.  Check the log just above the summary and you will have a summary of one state per line.

**Comment by smithfarm** [comment]
> Check the log just above the summary and you will have a summary of one state per line.

I would expect that to be there, too, but it's not. I'll try to figure out why.

**Comment by smithfarm** [comment]
I have not been able to get stage 3 to fail when testing with https://github.com/SUSE/DeepSea/pull/455
