### ISSUE TITLE
Salt check

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#495]
One of the hardest problems to prevent is when someone starts Salt for the first time, runs a few commands that work fine and then proceeds to have DeepSea fail because a minion is "missing" a command.  For instance,

```
> cephinspector.inspect failed on ses4node2.qatest: The minion function caused
> an exception: Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1071, in
> _thread_return
>     return_data = func(*args, **kwargs)
>   File "/var/cache/salt/minion/extmods/modules/cephinspector.py", line 132,
> in inspect
>     for rs in __salt__['service.get_running']():
>   File "/usr/lib/python2.7/site-packages/salt/loader.py", line 900, in
> __getitem__
>     func = super(LazyLoader, self).__getitem__(item)
>   File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 93, in
> __getitem__
>     raise KeyError(key)
> KeyError: 'service.get_running'
> 
```

How a minion can answer 'cmd.shell' but is missing 'service.get_running' is beyond me.  I do think we can do a runtime check though.  Considering that Salt will add and deprecate states, modules, etc., we cannot simply whitelist what we think we need.  The maintenance would be too much.

However, we could add a Salt check to the validate runner that compares each minions `__salt__ ` structure.  It's not that the values need to be the same, just that all the keys match.  Otherwise, something is not available on a minion.  

This needs some investigation to determine if this is reliable.

**Comment by swiftgist** [comment]
Well, this is sad

```
# for i in `salt-key -L | grep ceph`
> do
>   salt $i sys.list_functions | wc -l
> done
1807
1684
1684
1684
1636
1684
1636
1636
1684
1638
1638
1638
1686
1686
1686
1636
1684
1684
1684
1636
1684
1684
1684
```

I somewhat expected that all minions with Ceph installed would have equivalent Salt dependencies.  This is on my working VM cluster where the Vagrant machines start from the same image.  I can almost see the salt-master at 1807, but the rest aren't even grouped by function.
