### ISSUE TITLE
Recent changes to populate cause stage 3 to fail **REGRESSION**

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#580]
PR https://github.com/SUSE/DeepSea/pull/566 seems to have caused almost all the regression tests to start failing:

http://149.202.179.231:8081/ubuntu-2017-08-25_19:39:36-deepsea:basic-ses5---basic-openstack/

The following error appears throughout the stages:

```
2017-08-25T19:49:32.861 INFO:teuthology.orchestra.run.target217182143124.stdout:Traceback (most recent call last):
2017-08-25T19:49:32.861 INFO:teuthology.orchestra.run.target217182143124.stdout:  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1333, in _load_module
2017-08-25T19:49:32.862 INFO:teuthology.orchestra.run.target217182143124.stdout:    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
2017-08-25T19:49:32.862 INFO:teuthology.orchestra.run.target217182143124.stdout:  File "/srv/modules/runners/populate.py", line 28, in <module>
2017-08-25T19:49:32.862 INFO:teuthology.orchestra.run.target217182143124.stdout:    from validate import Validate, get_printer
2017-08-25T19:49:32.862 INFO:teuthology.orchestra.run.target217182143124.stdout:ImportError: cannot import name Validate
```

(This has been traced to this line https://github.com/SUSE/DeepSea/blob/65877ff9cbd69aeff591c6cd066f0e973ad5f509/srv/modules/runners/populate.py#L28 which was added in #566.)

But it's stage 3 that eventually fails, with:

```
2017-08-25T19:49:55.741 INFO:teuthology.orchestra.run.target217182143124.stdout:[ERROR   ] Run failed on minions: target217182143124.teuthology
2017-08-25T19:49:55.741 INFO:teuthology.orchestra.run.target217182143124.stdout:Failures:
2017-08-25T19:49:55.741 INFO:teuthology.orchestra.run.target217182143124.stdout:    target217182143124.teuthology:
2017-08-25T19:49:55.741 INFO:teuthology.orchestra.run.target217182143124.stdout:      Name: skip - Function: test.nop - Result: Clean Started: - 19:49:55.553844 Duration: 1.196 ms
2017-08-25T19:49:55.742 INFO:teuthology.orchestra.run.target217182143124.stdout:    ----------
2017-08-25T19:49:55.742 INFO:teuthology.orchestra.run.target217182143124.stdout:              ID: auth /srv/salt/ceph/mgr/cache/target217182143013.keyring
2017-08-25T19:49:55.742 INFO:teuthology.orchestra.run.target217182143124.stdout:        Function: cmd.run
2017-08-25T19:49:55.742 INFO:teuthology.orchestra.run.target217182143124.stdout:            Name: ceph auth add mgr.target217182143013 -i /srv/salt/ceph/mgr/cache/target217182143013.keyring
2017-08-25T19:49:55.742 INFO:teuthology.orchestra.run.target217182143124.stdout:          Result: False
2017-08-25T19:49:55.742 INFO:teuthology.orchestra.run.target217182143124.stdout:         Comment: Command "ceph auth add mgr.target217182143013 -i /srv/salt/ceph/mgr/cache/target217182143013.keyring" run
2017-08-25T19:49:55.743 INFO:teuthology.orchestra.run.target217182143124.stdout:         Started: 19:49:55.556700
2017-08-25T19:49:55.743 INFO:teuthology.orchestra.run.target217182143124.stdout:        Duration: 158.943 ms
2017-08-25T19:49:55.743 INFO:teuthology.orchestra.run.target217182143124.stdout:         Changes:
2017-08-25T19:49:55.743 INFO:teuthology.orchestra.run.target217182143124.stdout:                  ----------
2017-08-25T19:49:55.743 INFO:teuthology.orchestra.run.target217182143124.stdout:                  pid:
2017-08-25T19:49:55.743 INFO:teuthology.orchestra.run.target217182143124.stdout:                      24438
2017-08-25T19:49:55.743 INFO:teuthology.orchestra.run.target217182143124.stdout:                  retcode:
2017-08-25T19:49:55.744 INFO:teuthology.orchestra.run.target217182143124.stdout:                      1
2017-08-25T19:49:55.744 INFO:teuthology.orchestra.run.target217182143124.stdout:                  stderr:
2017-08-25T19:49:55.744 INFO:teuthology.orchestra.run.target217182143124.stdout:                      2017-08-25 19:49:55.684698 7fe7bfdd5700 -1 Errors while parsing config file!
2017-08-25T19:49:55.744 INFO:teuthology.orchestra.run.target217182143124.stdout:                      2017-08-25 19:49:55.684709 7fe7bfdd5700 -1 end of key=val line 8 reached, no "=val" found...missing =?
2017-08-25T19:49:55.744 INFO:teuthology.orchestra.run.target217182143124.stdout:                      2017-08-25 19:49:55.684710 7fe7bfdd5700 -1 end of key=val line 10 reached, no "=val" found...missing =?
2017-08-25T19:49:55.745 INFO:teuthology.orchestra.run.target217182143124.stdout:                      2017-08-25 19:49:55.684710 7fe7bfdd5700 -1 end of key=val line 11 reached, no "=val" found...missing =?
2017-08-25T19:49:55.745 INFO:teuthology.orchestra.run.target217182143124.stdout:                      2017-08-25 19:49:55.684711 7fe7bfdd5700 -1 end of key=val line 12 reached, no "=val" found...missing =?
2017-08-25T19:49:55.745 INFO:teuthology.orchestra.run.target217182143124.stdout:                      2017-08-25 19:49:55.684711 7fe7bfdd5700 -1 end of key=val line 13 reached, no "=val" found...missing =?
2017-08-25T19:49:55.745 INFO:teuthology.orchestra.run.target217182143124.stdout:                      2017-08-25 19:49:55.684713 7fe7bfdd5700 -1 end of key=val line 14 reached, no "=val" found...missing =?
2017-08-25T19:49:55.745 INFO:teuthology.orchestra.run.target217182143124.stdout:                      2017-08-25 19:49:55.684714 7fe7bfdd5700 -1 end of key=val line 15 reached, no "=val" found...missing =?
2017-08-25T19:49:55.745 INFO:teuthology.orchestra.run.target217182143124.stdout:                      2017-08-25 19:49:55.684714 7fe7bfdd5700 -1 end of key=val line 16 reached, no "=val" found...missing =?
2017-08-25T19:49:55.746 INFO:teuthology.orchestra.run.target217182143124.stdout:                      unable to parse addrs in 'The minion function caused an exception: Traceback (most recent call last):'
2017-08-25T19:49:55.746 INFO:teuthology.orchestra.run.target217182143124.stdout:                      InvalidArgumentError does not take keyword arguments
2017-08-25T19:49:55.746 INFO:teuthology.orchestra.run.target217182143124.stdout:                  stdout:
2017-08-25T19:49:55.746 INFO:teuthology.orchestra.run.target217182143124.stdout:                      server name not found: The (Name or service not known)
2017-08-25T19:49:55.746 INFO:teuthology.orchestra.run.target217182143124.stdout:
2017-08-25T19:49:55.747 INFO:teuthology.orchestra.run.target217182143124.stdout:    Summary for target217182143124.teuthology
2017-08-25T19:49:55.747 INFO:teuthology.orchestra.run.target217182143124.stdout:    ------------
2017-08-25T19:49:55.747 INFO:teuthology.orchestra.run.target217182143124.stdout:    Succeeded: 1 (changed=1)
2017-08-25T19:49:55.747 INFO:teuthology.orchestra.run.target217182143124.stdout:    Failed:    1
2017-08-25T19:49:55.747 INFO:teuthology.orchestra.run.target217182143124.stdout:    ------------
2017-08-25T19:49:55.747 INFO:teuthology.orchestra.run.target217182143124.stdout:    Total states run:     2
2017-08-25T19:49:55.748 INFO:teuthology.orchestra.run.target217182143124.stdout:    Total run time: 160.139 ms
2017-08-25T19:49:55.748 INFO:teuthology.orchestra.run.target217182143124.stdout:
```

The reason this happens is that ceph.conf gets populated with a traceback for the value of `mon_host`. Here's the first few lines of ceph.conf extracted from the test environment:

```
# DeepSea default configuration. Changes in this file will be overwritten on
# package update. Include custom configuration fragments in
# /srv/salt/ceph/configuration/files/ceph.conf.d/[global,osd,mon,mgr,mds,client].conf
[global]
fsid = 386358af-9ebf-3484-9cae-8962409c7fbd
mon_initial_members = target149202160024
mon_host = The minion function caused an exception: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1445, in _thread_return
    return_data = executor.execute()
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
    return self.func(*self.args, **self.kwargs)
  File "/var/cache/salt/minion/extmods/modules/public.py", line 40, in address
    ipaddress.ip_network(u'{}'.format(public_network))):
  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 196, in ip_network
    address)
ValueError: u'149.202.160.24/32, 149.202.160.240/32' does not appear to be an IPv4 or IPv6 network

auth_cluster_required = cephx
auth_service_required = cephx
auth_client_required = cephx
filestore_xattr_use_omap = true
public_network = 149.202.160.24/32, 149.202.160.240/32
cluster_network = 149.202.160.24/32, 149.202.160.240/32
```

Unfortunately it was not visible in the log because ceph.conf doesn't get dumped to the log until after Stage 3 completes, and only when it completes successfully :-(

NOTE: This is with the very latest ses5 branch (with latest luminous) using "make install" to install DeepSea in a pristine environment.

**Comment by smithfarm** [comment]
Here's a full log showing how the deployment fails: http://149.202.179.231:8081/ubuntu-2017-08-25_21:24:22-deepsea:basic:fs-ses5---basic-openstack/ (click on the little "LOG" icon)

(Note that the salt debug messages make the log extremely noisy - I recommend searching for strings from the errors quoted above. Also I've found it helps sometimes to search for "running DeepSea" because that string appears in the log just before each stage begins.)

**Comment by smithfarm** [comment]
And here's a full "suites/basic" run showing how the regression causes all the tests to fail except for the most basic health-ok.sh test: http://149.202.179.231:8081/ubuntu-2017-08-25_19:39:36-deepsea:basic-ses5---basic-openstack/

**Comment by smithfarm** [comment]
Added more details to the issue description.

**Comment by smithfarm** [comment]
I found the issue! Issue description updated again.

**Comment by swiftgist** [comment]
vpn seems to be down for me at the moment... That makes sense about ceph.conf.  Still unsure about the exact fix for the import.

**Comment by smithfarm** [comment]
I re-ran the test with #581 and am pleased to confirm that the `ImportError: cannot import name Validate` tracebacks are gone. However, `mon_host` is still getting populated with a traceback in `ceph.conf` so the rest of the issue description still stands.

**Comment by smithfarm** [comment]
The problem arises in this line https://github.com/SUSE/DeepSea/blob/e9ffafc41fe77f38557cafb9b2403e75677ae7f1/srv/salt/_modules/public.py#L40 which was added in https://github.com/SUSE/DeepSea/pull/575

In ceph.conf, `public_network` is set to "149.202.160.24/32, 149.202.160.240/32" which causes that line to barf out the traceback, which enters `ceph.conf` as the value of `mon_host`.

**Comment by swiftgist** [comment]
public.py only has public.address... the public_network is coming from the pillar.  It's put there by populate.py.

**Comment by smithfarm** [comment]
It's pretty clear what's happening. I dug up the minion log:

```
2017-08-25 23:16:57,531 [salt.loader.target149202170163.teuthology.ext.module.public][DEBUG   ][21084] networks: ['149.202.170.163/32, 149.202.170.164/32']
...
2017-08-25 23:16:57,531 [salt.loader.target149202170163.teuthology.ext.module.public][INFO    ][21084] public_network: 149.202.170.163/32, 149.202.170.164/32
```

and then:

`2017-08-25 23:16:57,682 [salt.utils.event ][DEBUG   ][20922] Sending event: tag = salt/run/20170825231656665083/ret; data = {'fun_args': [{'cluster': 'ceph', 'roles': 'mon'}], 'jid': '20170825231656665083', 'return': ['The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1445, in _thread_return\n    return_data = executor.execute()\n  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File "/var/cache/salt/minion/extmods/modules/public.py", line 40, in address\n    ipaddress.ip_network(u\'{}\'.format(public_network))):\n  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 196, in ip_network\n    address)\nValueError: u\'149.202.170.163/32, 149.202.170.164/32\' does not appear to be an IPv4 or IPv6 network\n'], 'success': True, '_stamp': '2017-08-25T23:16:57.682697', 'user': 'UNKNOWN', 'fun': 'runner.select.public_addresses'}`

**Comment by smithfarm** [comment]
The point being that `public_network` might be a comma-separated string of networks, and public.py does not seem to treat that possibility.

**Comment by smithfarm** [comment]
Added "regression" to the issue title because the multiple subnets worked fine before the latest changes.

**Comment by smithfarm** [comment]
This one is getting kinda long; closing in favor of #582.
