### ISSUE TITLE
Inconsistent ownership of files and directories under /srv/salt/ceph causes Permission Denied in config.changed runner

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#675]
The runner runs as the user `salt`, which does not have write permissions on the directory `/srv/salt/ceph/configuration/files`:

`17-09-21T17:39:59.793 INFO:teuthology.orchestra.run.target149202164133.stdout:[DEBUG   ] Sending event: tag = salt/run/20170921173958639556/ret; data = {'fun_args': [{'service': 'rgw'}], 'jid': '20170921173958639556', 'return': 'Exception occurred in runner changed.config: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/srv/modules/runners/changed.py", line 154, in config\n    return requires_conf_change(service)\n  File "/srv/modules/runners/changed.py", line 131, in requires_conf_change\n    if Config(deps).has_change():\n  File "/srv/modules/runners/changed.py", line 119, in has_change\n    self.write_checksum(current_cs)\n  File "/srv/modules/runners/changed.py", line 89, in write_checksum\n    with open(self.checksum_file, \'w\') as fd:\nIOError: [Errno 13] Permission denied: \'/srv/salt/ceph/configuration/files/ceph.conf.checksum/rgw.conf\'\n', 'success': False, '_stamp': '2017-09-21T17:39:59.777625', 'user': 'UNKNOWN', 'fun': 'runner.changed.config'}`

**Comment by smithfarm** [comment]
This could be fixed by making all files installed by DeepSea in `/srv/salt/ceph` writable by the user `salt`. (Currently only root can write to them.) There are two ways to accomplish this: 

1. install the entire tree with ownership salt:salt (essentially `chown -R salt:salt /srv/salt/ceph` but leave the permissions as they are)
2. install the entire tree with ownership root:salt (essentially `chown -R root:salt /srv/salt/ceph ; chmod -R g+w /srv/salt/ceph`)

Another option would be to continue with the current piecemeal approach and add this particular directory `/srv/salt/ceph/configuration/files/` to the list of files/directories with ownership salt:salt.

**Comment by smithfarm** [comment]
Opened https://bugzilla.suse.com/show_bug.cgi?id=1059886 to get more input.

**Comment by smithfarm** [comment]
Oops, I was misunderstanding how permissions work. As long as the directory is owned by salt and owner has write and execute permissions on the directory, the owner can write to it. The problem here was that the owner lacked execute permissions.

Opened #676 with the fix.
