### ISSUE TITLE
deepsea CLI breaks when LC_ALL=C 

### ISSUE THREAD

**Issue by fghaas** [SUSE/DeepSea#688]
The deepsea CLI appears to choke on the unicode check mark (✓) when `LC_ALL` is set to C.

```
$ sudo deepsea stage run ceph.stage.prep
Starting stage: ceph.stage.prep
Parsing ceph.stage.prep steps... Traceback (most recent call last):
  File "/usr/bin/deepsea", line 9, in <module>
    load_entry_point('deepsea==0.7.27+git.0.274c55d', 'console_scripts', 'deepsea')()
  File "/usr/lib/python2.7/site-packages/deepsea/deepsea.py", line 311, in main
    cli(prog_name='deepsea')
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/deepsea/deepsea.py", line 269, in stage_run
    ret = run_stage(stage_name, hide_state_steps, hide_dynamic_steps, simple_output)
  File "/usr/lib/python2.7/site-packages/deepsea/stage_executor.py", line 77, in run_stage
    mon.parse_stage(stage_name)
  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 505, in parse_stage
    self._fire_event('stage_parsing_started', stage_name)
  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 569, in _fire_event
    getattr(listener, event)(*args)
  File "/usr/lib/python2.7/site-packages/deepsea/monitors/terminal_outputter.py", line 600, in stage_parsing_started
    PP.println(SP.WAITING)
  File "/usr/lib/python2.7/site-packages/deepsea/common.py", line 220, in println
    sys.stdout.write(u"{}\n".format(text))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u23f3' in position 11: ordinal not in range(128)
```

Compare:

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```

Exporting `LC_ALL=en_US.UTF-8` fixes the problem, but you may want to consider either checking for proper UTF-8 support on the console, or just use `OK` in place of `✓`.

**Comment by fghaas** [comment]
Correction: actually, the initial error message is about the hourglass (⏳), not the check mark (✓). But the same issue applies, either way.

**Comment by rjfd** [comment]
@fghaas good catch. I'll try to detect if UTF-8 is supported and use the images in the positive case only.

I've also added a a simple B&W outputter, which is usually used for testing purposes, but can also be used in very "old" terminals. You can activate this outputter like this:

```
deepsea stage run ceph.stage.0 --simple-output
```

**Comment by fghaas** [comment]
@rjfd, can confirm — works fine with `--simple-output`, even with `LC_ALL=C`. Thanks!

**Comment by rjfd** [comment]
@fghaas in the meantime I already open PR #691  for fixing the normal outputter when no UTF-8 glyphs are supported.
