### ISSUE TITLE
cli: error while processing execution failures

### ISSUE THREAD

**Issue by rjfd** [SUSE/DeepSea#803]
The below error was triggered while testing a patch for issuer #793 

```
[20/36]   state.orchestrate(mods=['ceph.restart'])................... ❌ (19s)
            |_ changed.mon........................................... ✓ (0.5s)
            |_ cephprocesses.restart_required(role=mon).............. ✓ (0.3s)
                 |_ cephprocesses.restart_required(role=mon) on
                    mon1.ceph........................................ ✓ (0.1s)
            |_ cephprocesses.restart_required(role=mgr).............. ✓ (0.4s)
                 |_ cephprocesses.restart_required(role=mgr) on
                    mon1.ceph........................................ ✓ (0.2s)
            |_ changed.osd........................................... ✓ (0.4s)
            |_ cephprocesses.restart_required(role=storage).......... ✓ (0.8s)
                 |_ cephprocesses.restart_required(role=storage) on
                    data1.ceph....................................... ✓ (0.6s)
            |_ changed.rgw........................................... ✓ (0.6s)
            |_ cephprocesses.restart_required(role=rgw).............. ✓ (0.1s)
            |_ changed.mds........................................... ✓ (0.4s)
            |_ cephprocesses.restart_required(role=mds).............. ✓ (0.1s)
            |_ cephprocesses.restart_required(role=igw).............. ✓ (0.1s)
            |_ cephprocesses.restart_required(role=ganesha).......... ✓ (0.1s)
            |_ cephprocesses.restart_required(role=openattic)........ ✓ (0.1s)
 
Ended stage: ceph.stage.0 succeeded=19/36 failed=1/36 time=51.6s
 
Failures summary:
 
state.orchestrate:
> /usr/lib/python2.7/site-packages/deepsea/monitors/terminal_outputter.py(760)stage_finished()
-> for line in traceback.split('\n'):
(Pdb) traceback
{'outputter': 'highstate', 'data': {'admin.ceph_master': {}}, 'retcode': 1}
(Pdb) c
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 576, in run
    event.call()
  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 461, in call
    getattr(self.monitor, self.func)(self.event)
  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 634, in end_stage
    self._fire_event('stage_finished', tmp_stage)
  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 592, in _fire_event
    getattr(listener, event)(*args)
  File "/usr/lib/python2.7/site-packages/deepsea/monitors/terminal_outputter.py", line 760, in stage_finished
    for line in traceback.split('\n'):
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by rjfd** [comment]
@jschmid1 can you give more details on how to reproduce the issue? like which stage were you running?

**Comment by jschmid1** [comment]
@rjfd In the the patch I mentioned in the #793, I tried to invoke ceph.restart(orchestration) in stage.0(orchestration). This is something we haven't done so far and is not quite covered in the upstream salt docs.

When the call fails, it's return is: `{'outputter': 'highstate', 'data': {'admin.ceph_master': {}}, 'retcode': 1}` which is not handled in the cli code. 

However, I'm not yet sure that I'll go that route, hence there's no need to fix that yet. I'll update this issue to keep you informed.

**Comment by rjfd** [comment]
@jschmid1 thanks!
