### ISSUE TITLE
Stage 0 fails because salt-api is deployed before module sync

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#914]
This is the "deepsea.user" issue, which may or may not be related to #911 but is definitely giving me grief in #908.

In the first run of Stage 0, Python code that is running on a minion fails to load with:

```
2018-01-28T01:05:20.732 INFO:teuthology.orchestra.run.target137074029186.stdout:[INFO    ] {'ret': {'target137074029186.teuthology': {'module_|-switch kernel_|-kernel.replace_|-run': {'comment': 'Module function kernel.replace executed', 'name': 'kernel.replace', 'start_time': '01:04:49.221964', 'result': True, 'duration': 60.837, '__run_num__': 0, 'changes': {'ret': None}, '__id__': 'switch kernel'}, 'module_|-packagemanager patch only kernel_|-packagemanager.up_|-run': {'comment': 'Module function packagemanager.up executed', 'name': 'packagemanager.up', 'start_time': '01:04:49.283163', 'result': True, 'duration': 27061.075, '__run_num__': 1, 'changes': {'ret': None}, '__id__': 'packagemanager patch only kernel'}, 'module_|-packagemanager update regular_|-packagemanager.up_|-run': {'comment': 'Module function packagemanager.up executed', 'name': 'packagemanager.up', 'start_time': '01:05:16.362088', 'result': True, 'duration': 4227.214, '__run_num__': 2, 'changes': {'ret': None}, '__id__': 'packagemanager update regular'}}}, 'out': 'highstate'}
2018-01-28T01:05:20.732 INFO:teuthology.orchestra.run.target137074029186.stdout:[INFO    ] Completed state [prepare master] at time 01:05:20.732010 duration_in_ms=31814.436
2018-01-28T01:05:20.733 INFO:teuthology.orchestra.run.target137074029186.stdout:[INFO    ] Running state [filequeue.remove] at time 01:05:20.732744
2018-01-28T01:05:20.734 INFO:teuthology.orchestra.run.target137074029186.stdout:[INFO    ] Executing state salt.runner for filequeue.remove
2018-01-28T01:05:20.786 INFO:teuthology.orchestra.run.target137074029186.stdout:[DEBUG   ] LazyLoaded boto.assign_funcs
2018-01-28T01:05:21.018 INFO:teuthology.orchestra.run.target137074029186.stdout:[DEBUG   ] Failed to import module kubernetes:
2018-01-28T01:05:21.018 INFO:teuthology.orchestra.run.target137074029186.stdout:Traceback (most recent call last):
2018-01-28T01:05:21.019 INFO:teuthology.orchestra.run.target137074029186.stdout:  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1333, in _load_module
2018-01-28T01:05:21.019 INFO:teuthology.orchestra.run.target137074029186.stdout:    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
2018-01-28T01:05:21.019 INFO:teuthology.orchestra.run.target137074029186.stdout:  File "/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py", line 67, in <module>
2018-01-28T01:05:21.019 INFO:teuthology.orchestra.run.target137074029186.stdout:    from kubernetes.client import AppsV1beta1Deployment
2018-01-28T01:05:21.019 INFO:teuthology.orchestra.run.target137074029186.stdout:  File "/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py", line 67, in <module>
2018-01-28T01:05:21.020 INFO:teuthology.orchestra.run.target137074029186.stdout:    from kubernetes.client import AppsV1beta1Deployment
2018-01-28T01:05:21.020 INFO:teuthology.orchestra.run.target137074029186.stdout:ImportError: No module named client
```

This leads to:

```
2018-01-28T01:06:23.303 INFO:teuthology.orchestra.run.target137074029186.stdout:target137074029186.teuthology_master:
2018-01-28T01:06:23.303 INFO:teuthology.orchestra.run.target137074029186.stdout:----------
2018-01-28T01:06:23.303 INFO:teuthology.orchestra.run.target137074029186.stdout:          ID: salt-api
2018-01-28T01:06:23.303 INFO:teuthology.orchestra.run.target137074029186.stdout:    Function: salt.state
2018-01-28T01:06:23.303 INFO:teuthology.orchestra.run.target137074029186.stdout:      Result: False
2018-01-28T01:06:23.303 INFO:teuthology.orchestra.run.target137074029186.stdout:     Comment: Run failed on minions: target137074029186.teuthology
2018-01-28T01:06:23.303 INFO:teuthology.orchestra.run.target137074029186.stdout:              Failures:
2018-01-28T01:06:23.304 INFO:teuthology.orchestra.run.target137074029186.stdout:                  target137074029186.teuthology:
2018-01-28T01:06:23.304 INFO:teuthology.orchestra.run.target137074029186.stdout:                      Data failed to compile:
2018-01-28T01:06:23.304 INFO:teuthology.orchestra.run.target137074029186.stdout:                  ----------
2018-01-28T01:06:23.304 INFO:teuthology.orchestra.run.target137074029186.stdout:                      Rendering SLS 'base:ceph.salt-api.configure' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'deepsea.user'
```

and failure of the stage as a whole.

**Comment by smithfarm** [comment]
Ah, I see @denisok has a patch here: https://github.com/SUSE/DeepSea/pull/902

Not sure if that addresses the `import kubernetes` issue, though.

**Comment by denisok** [comment]
> [DEBUG   ] Checking whether jid 20180129174958322969 is still running
> [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'admin.ceph_master', 'tcp:
> //127.0.0.1:4506', 'clear')
> [DEBUG   ] Passing on saltutil error. This may be an error in saltclient. 'retcode'
> [DEBUG   ] jid 20180129174958322969 return from admin.ceph
> [DEBUG   ] jid 20180129174958322969 found all minions set(['admin.ceph'])
> [INFO    ] {'ret': {'admin.ceph': {'module_|-switch kernel_|-kernel.replace_|-run': {'comment': 'Module f
> unction kernel.replace executed', 'name': 'kernel.replace', 'start_time': '17:49:58.634176', 'result': Tr
> ue, 'duration': 13.373, '__run_num__': 0, 'changes': {'ret': None}, '__id__': 'switch kernel'}, 'module_|
> -packagemanager patch only kernel_|-packagemanager.up_|-run': {'comment': 'Module function packagemanager
> .up executed', 'name': 'packagemanager.up', 'start_time': '17:49:58.647773', 'result': True, 'duration':
> 8070.409, '__run_num__': 1, 'changes': {'ret': None}, '__id__': 'packagemanager patch only kernel'}, 'mod
> ule_|-packagemanager update regular_|-packagemanager.up_|-run': {'comment': 'Module function packagemanag
> er.up executed', 'name': 'packagemanager.up', 'start_time': '17:50:06.728563', 'result': True, 'duration'
> : 426.953, '__run_num__': 2, 'changes': {'ret': None}, '__id__': 'packagemanager update regular'}}}, 'out
> ': 'highstate'}
> [INFO    ] Completed state [prepare master] at time 17:50:07.284603 duration_in_ms=9054.332
> [INFO    ] Running state [filequeue.remove] at time 17:50:07.285080
> [INFO    ] Executing state salt.runner for filequeue.remove
> [DEBUG   ] Module DSC: Only available on Windows systems
> [DEBUG   ] Module PSGet: Only available on Windows systems
> [DEBUG   ] Failed to import module kubernetes:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1333, in _load_module
>     mod = imp.load_module(mod_namespace, fn_, fpath, desc)
>   File "/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py", line 63, in <module>
>     from kubernetes.client import AppsV1beta1Deployment
>   File "/usr/lib/python2.7/site-packages/salt/modules/kubernetes.py", line 63, in <module>
>     from kubernetes.client import AppsV1beta1Deployment
> ImportError: No module named client
> [DEBUG   ] Could not LazyLoad reg.read_value: 'reg' __virtual__ returned False: reg execution module fail
> ed to load: The module will only run on Windows systems
> [DEBUG   ] LazyLoaded boto_kms.describe_key
> [DEBUG   ] LazyLoaded boto_elasticache.exists
> [DEBUG   ] LazyLoaded zk_concurrency.lock
> [DEBUG   ] LazyLoaded nxos.cmd
> [DEBUG   ] LazyLoaded boto_vpc.exists
> [DEBUG   ] LazyLoaded boto_s3_bucket.exists
> [DEBUG   ] LazyLoaded splunk_search.get

could reproduce it with sle12sp3 vagrant box. Run it with debug, looks like LazyLoad reloads all the modules it could find.

**Comment by denisok** [comment]
yes, this exception is just ignored. So real problem is different. Could you reproduce it with ` salt-run state.orch ceph.stage.0 --log-level=debug` ?

**Comment by smithfarm** [comment]
@denisok Yes, full debug-level console log is here: https://paste2.org/7ts5tH8O

**Comment by smithfarm** [comment]
I can also provide debug-level minion logs.

**Comment by smithfarm** [comment]
@denisok That particular test job had only one node, so there is only one minion log. Here it is: https://paste2.org/NsyFnAZs

**Comment by smithfarm** [comment]
Wow, that minion log is BIZARRE
