### ISSUE TITLE
net.ping no longer works

### ISSUE THREAD

**Issue by jan--f** [SUSE/DeepSea#959]
```
salt-run net.ping
[WARNING ] Unable to find IPv6 record for "admin" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
Exception occurred in runner net.ping: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/modules/runners/net.py", line 358, in ping
    _summarize(len(addresses), results)
  File "/srv/modules/runners/net.py", line 458, in _summarize
    if results[host]['succeeded'] == total:
TypeError: string indices must be integers, not str
```

**Comment by swiftgist** [comment]
Hmm, I just ran this without issue.

```
# salt-run net.ping
[WARNING ] Unable to find IPv6 record for "admin.ceph" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
Succeeded: 92 addresses from 23 minions average rtt 50.34 ms
```

**Comment by Martin-Weiss** [comment]
If I remember right we had this problem on a system that does not have ipv6 enabled at all.
So could this be fixed also without adding ipv6 to dns and hosts?
