### ISSUE TITLE
stage1 passes silently though populate fails 

### ISSUE THREAD

**Issue by theanalyst** [SUSE/DeepSea#97]
In a virtual setup I'm getting a success for stage1 even though populate proposals runner has errored out
```sh
# salt-run state.orch ceph.stage.1
[WARNING ] All minions are ready
retcode:
    0
7374-deepsea-salt-master_master:
  Name: minions.ready - Function: salt.runner - Result: Changed Started: - 16:37:17.294890 Duration: 1477.662 ms
  Name: populate.proposals - Function: salt.runner - Result: Changed Started: - 16:37:18.772688 Duration: 1767.664 ms

Summary for 7374-deepsea-salt-master_master
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:   3.245 s

bash-4.3# salt-run populate.proposals                    
Exception occurred in runner populate.proposals: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 357, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/modules/runners/populate.py", line 829, in proposals
    disk_configuration.generate(hardwareprofile)
  File "/srv/modules/runners/populate.py", line 297, in generate
    self.hardware.add(server, self.storage_nodes[server])
  File "/srv/modules/runners/populate.py", line 178, in add
    label = self._label(drive['Model'], drive['Capacity'])
KeyError: 'Capacity'
```
hwinfo does list the capacity though, part of output from cephdisks.list mine function

```
374-deepsea-salt-minion-b:
    |_
      ----------
      Attached to:
          #15 (Storage controller)
      Bytes:
          8589934592
      Capacity:
          8 GB
      Config Status:
          cfg=new, avail=yes, need=no, active=unknown
      Device File:
          /dev/vdb
      Device Number:
          block 254:16-254:31
      Driver:
          virtio-pci, virtio_blk
      Driver Modules:
          virtio_pci, virtio_blk
      Geometry (Logical):
          CHS 16644/16/63
      Hardware Class:
          disk
      Model:
          Disk
      Parent ID:
          sNGd.+FFPFBVXZu6
      Size:
          16777216 sectors a 512 bytes
      SysFS BusID:
          virtio1
      SysFS Device Link:
          /devices/pci0000:00/0000:00:04.0/virtio1
      SysFS ID:
          /class/block/vdb
      Unique ID:
          ndrI.Fxp0d3BezAE
      device:
          vdb
      rotational:
          1
```

**Comment by theanalyst** [comment]
This case arose because salt had permission to read only one of the devices 
(which was supposed to be the osd) and the other devices were not having permissions to read by hwinfo, I'm not sure whether someone will create fine grained permissions like that, but if they do we raise an exception if certain fields of hwinfo are not populated instead of passing through and dropping the device from the list

**Comment by jan--f** [comment]
Can we close this @theanalyst ?

**Comment by theanalyst** [comment]
Not sure whether relevant but we do fail when we don't have permissions to read a device instead of skipping it, not sure whether this might come up in prod. scenarios

**Comment by jschmid1** [comment]
I did this here: 

https://github.com/SUSE/DeepSea/blob/master/srv/salt/_modules/cephdisks.py#L399

Still, I can't recall if Exceptions raised by a module will be passed through if the module is invoked by a runner, like in our case. 

`salt-run populate.proposals`
