### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'raw_event' in repeat Stage 0

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#978]
The `health-openattic.sh` test script in SES5 branch runs stages 0-4 to deploy openATTIC, and then runs Stage 0 a second time. Sometimes, during this repeat run of Stage 0, the following error appears:

```
2018-03-03T11:27:49.038 INFO:teuthology.orchestra.run.target137074029221.stdout:[72/83] Executing state ceph.wait...
2018-03-03T11:28:23.656 INFO:teuthology.orchestra.run.target137074029221.stdout:         |_  target137074029221.teuthology: wait(wait.out) oException in thread Thread-1:
2018-03-03T11:28:23.657 INFO:teuthology.orchestra.run.target137074029221.stdout:Traceback (most recent call last):
2018-03-03T11:28:23.658 INFO:teuthology.orchestra.run.target137074029221.stdout:  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
2018-03-03T11:28:23.658 INFO:teuthology.orchestra.run.target137074029221.stdout:    self.run()
2018-03-03T11:28:23.658 INFO:teuthology.orchestra.run.target137074029221.stdout:  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 576, in run
2018-03-03T11:28:23.658 INFO:teuthology.orchestra.run.target137074029221.stdout:    event.call()
2018-03-03T11:28:23.658 INFO:teuthology.orchestra.run.target137074029221.stdout:  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 461, in call
2018-03-03T11:28:23.659 INFO:teuthology.orchestra.run.target137074029221.stdout:    getattr(self.monitor, self.func)(self.event)
2018-03-03T11:28:23.659 INFO:teuthology.orchestra.run.target137074029221.stdout:  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 634, in end_stage
2018-03-03T11:28:23.659 INFO:teuthology.orchestra.run.target137074029221.stdout:    self._fire_event('stage_finished', tmp_stage)
2018-03-03T11:28:23.660 INFO:teuthology.orchestra.run.target137074029221.stdout:  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 592, in _fire_event
2018-03-03T11:28:23.660 INFO:teuthology.orchestra.run.target137074029221.stdout:    getattr(listener, event)(*args)
2018-03-03T11:28:23.661 INFO:teuthology.orchestra.run.target137074029221.stdout:  File "/usr/lib/python2.7/site-packages/deepsea/monitors/terminal_outputter.py", line 124, in stage_finished
2018-03-03T11:28:23.661 INFO:teuthology.orchestra.run.target137074029221.stdout:    traceback = error.raw_event['data']['return']
2018-03-03T11:28:23.661 INFO:teuthology.orchestra.run.target137074029221.stdout:AttributeError: 'NoneType' object has no attribute 'raw_event'
2018-03-03T11:28:23.662 INFO:teuthology.orchestra.run.target137074029221.stdout:
2018-03-03T11:28:24.975 INFO:teuthology.orchestra.run.target137074029221.stdout:k
2018-03-03T11:28:24.976 INFO:teuthology.orchestra.run.target137074029221.stdout:         target137074029221.teuthology... ok
```

(Strangely, there seems to be a rogue "k" character in the CLI output)

The stage ends with:

```
2018-03-03T11:28:24.982 INFO:teuthology.orchestra.run.target137074029221.stdout:Finished stage ceph.stage.0: succeeded=82/83 failed=1/83
2018-03-03T11:28:24.982 INFO:teuthology.orchestra.run.target137074029221.stdout:
2018-03-03T11:28:24.982 INFO:teuthology.orchestra.run.target137074029221.stdout:Failures summary:
2018-03-03T11:28:24.982 INFO:teuthology.orchestra.run.target137074029221.stdout:filequeue.remove (/srv/modules/runners/filequeue.py):
2018-03-03T11:28:25.015 INFO:teuthology.orchestra.run.target137074029221.stderr:+ deepsea_exit_status=0
2018-03-03T11:28:25.016 INFO:teuthology.orchestra.run.target137074029221.stderr:+ echo 'deepsea exit status: 0'
2018-03-03T11:28:25.016 INFO:teuthology.orchestra.run.target137074029221.stderr:+ '[' 0 = 0 ']'
2018-03-03T11:28:25.016 INFO:teuthology.orchestra.run.target137074029221.stderr:+ grep -q -F failed=0 /tmp/deepsea.0.log
2018-03-03T11:28:25.016 INFO:teuthology.orchestra.run.target137074029221.stdout:deepsea exit status: 0
2018-03-03T11:28:25.017 INFO:teuthology.orchestra.run.target137074029221.stdout:ERROR: deepsea stage returned exit status 0, yet one or more steps failed. Bailing out!
2018-03-03T11:28:25.017 INFO:teuthology.orchestra.run.target137074029221.stderr:+ echo 'ERROR: deepsea stage returned exit status 0, yet one or more steps failed. Bailing out!'
```

**Comment by smithfarm** [comment]
Logs are here: http://149.202.189.241/ubuntu-2018-03-03_10:55:45-deepsea:basic-wip-ses5-12.2.4---basic-openstack/30/

I saved the logs on my laptop in `~/deepsea/issues/978` so we can still access them after the URL goes bad.
